//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthSessionMode.
const (
	AuthSessionModeAPIOnly   AuthSessionMode = "api_only"
	AuthSessionModeAnonymous AuthSessionMode = "anonymous"
	AuthSessionModeSaml      AuthSessionMode = "saml"
)

// Valid indicates whether the value is a known member of the AuthSessionMode enum.
func (e AuthSessionMode) Valid() bool {
	switch e {
	case AuthSessionModeAPIOnly:
		return true
	case AuthSessionModeAnonymous:
		return true
	case AuthSessionModeSaml:
		return true
	default:
		return false
	}
}

// Defines values for CodexProfileEffort.
const (
	CodexProfileEffortHigh    CodexProfileEffort = "high"
	CodexProfileEffortLow     CodexProfileEffort = "low"
	CodexProfileEffortMax     CodexProfileEffort = "max"
	CodexProfileEffortMedium  CodexProfileEffort = "medium"
	CodexProfileEffortMinimal CodexProfileEffort = "minimal"
	CodexProfileEffortNone    CodexProfileEffort = "none"
	CodexProfileEffortUltra   CodexProfileEffort = "ultra"
	CodexProfileEffortXhigh   CodexProfileEffort = "xhigh"
)

// Valid indicates whether the value is a known member of the CodexProfileEffort enum.
func (e CodexProfileEffort) Valid() bool {
	switch e {
	case CodexProfileEffortHigh:
		return true
	case CodexProfileEffortLow:
		return true
	case CodexProfileEffortMax:
		return true
	case CodexProfileEffortMedium:
		return true
	case CodexProfileEffortMinimal:
		return true
	case CodexProfileEffortNone:
		return true
	case CodexProfileEffortUltra:
		return true
	case CodexProfileEffortXhigh:
		return true
	default:
		return false
	}
}

// Defines values for CodexProfilePersonality.
const (
	CodexProfilePersonalityFriendly  CodexProfilePersonality = "friendly"
	CodexProfilePersonalityNone      CodexProfilePersonality = "none"
	CodexProfilePersonalityPragmatic CodexProfilePersonality = "pragmatic"
)

// Valid indicates whether the value is a known member of the CodexProfilePersonality enum.
func (e CodexProfilePersonality) Valid() bool {
	switch e {
	case CodexProfilePersonalityFriendly:
		return true
	case CodexProfilePersonalityNone:
		return true
	case CodexProfilePersonalityPragmatic:
		return true
	default:
		return false
	}
}

// Defines values for CodexProfileSummary.
const (
	CodexProfileSummaryAuto     CodexProfileSummary = "auto"
	CodexProfileSummaryConcise  CodexProfileSummary = "concise"
	CodexProfileSummaryDetailed CodexProfileSummary = "detailed"
	CodexProfileSummaryNone     CodexProfileSummary = "none"
)

// Valid indicates whether the value is a known member of the CodexProfileSummary enum.
func (e CodexProfileSummary) Valid() bool {
	switch e {
	case CodexProfileSummaryAuto:
		return true
	case CodexProfileSummaryConcise:
		return true
	case CodexProfileSummaryDetailed:
		return true
	case CodexProfileSummaryNone:
		return true
	default:
		return false
	}
}

// Defines values for OccurrenceState.
const (
	Accepted    OccurrenceState = "accepted"
	Cancelled   OccurrenceState = "cancelled"
	Dispatching OccurrenceState = "dispatching"
	Failed      OccurrenceState = "failed"
	Pending     OccurrenceState = "pending"
	Skipped     OccurrenceState = "skipped"
)

// Valid indicates whether the value is a known member of the OccurrenceState enum.
func (e OccurrenceState) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Cancelled:
		return true
	case Dispatching:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Skipped:
		return true
	default:
		return false
	}
}

// Defines values for ProfileHarness.
const (
	Codex ProfileHarness = "codex"
)

// Valid indicates whether the value is a known member of the ProfileHarness enum.
func (e ProfileHarness) Valid() bool {
	switch e {
	case Codex:
		return true
	default:
		return false
	}
}

// Defines values for SessionMode.
const (
	New   SessionMode = "new"
	Reuse SessionMode = "reuse"
)

// Valid indicates whether the value is a known member of the SessionMode enum.
func (e SessionMode) Valid() bool {
	switch e {
	case New:
		return true
	case Reuse:
		return true
	default:
		return false
	}
}

// Defines values for SettingsBrowserAuth.
const (
	SettingsBrowserAuthAPIOnly   SettingsBrowserAuth = "api_only"
	SettingsBrowserAuthAnonymous SettingsBrowserAuth = "anonymous"
	SettingsBrowserAuthSaml      SettingsBrowserAuth = "saml"
)

// Valid indicates whether the value is a known member of the SettingsBrowserAuth enum.
func (e SettingsBrowserAuth) Valid() bool {
	switch e {
	case SettingsBrowserAuthAPIOnly:
		return true
	case SettingsBrowserAuthAnonymous:
		return true
	case SettingsBrowserAuthSaml:
		return true
	default:
		return false
	}
}

// Defines values for Status.
const (
	Active Status = "active"
	Paused Status = "paused"
)

// Valid indicates whether the value is a known member of the Status enum.
func (e Status) Valid() bool {
	switch e {
	case Active:
		return true
	case Paused:
		return true
	default:
		return false
	}
}

// AuthSession defines model for AuthSession.
type AuthSession struct {
	Authenticated bool `json:"authenticated"`

	// CanManageAll Can manage all schedules and assign or clear their owners. True for configured SAML admins, valid Bearer keys and anonymous mode.
	CanManageAll bool                         `json:"can_manage_all"`
	ExpiresAt    nullable.Nullable[time.Time] `json:"expires_at"`
	Mode         AuthSessionMode              `json:"mode"`
	ReadAccess   bool                         `json:"read_access"`
	User         nullable.Nullable[struct {
		DisplayName string `json:"display_name"`

		// Email Normalized email from the SAML identity, or null when unavailable.
		Email   nullable.Nullable[string] `json:"email"`
		Subject string                    `json:"subject"`
	}] `json:"user"`

	// WriteAccess Can create schedules and modify those available to this caller. SAML users without an email cannot write.
	WriteAccess bool `json:"write_access"`
}

// AuthSessionMode defines model for AuthSession.Mode.
type AuthSessionMode string

// CodexProfile defines model for CodexProfile.
type CodexProfile struct {
	Effort      *CodexProfileEffort      `json:"effort,omitempty"`
	Personality *CodexProfilePersonality `json:"personality,omitempty"`
	ServiceTier *string                  `json:"service_tier,omitempty"`
	Summary     *CodexProfileSummary     `json:"summary,omitempty"`
}

// CodexProfileEffort defines model for CodexProfile.Effort.
type CodexProfileEffort string

// CodexProfilePersonality defines model for CodexProfile.Personality.
type CodexProfilePersonality string

// CodexProfileSummary defines model for CodexProfile.Summary.
type CodexProfileSummary string

// CreateSchedule defines model for CreateSchedule.
type CreateSchedule struct {
	Cron  string                    `json:"cron"`
	Model nullable.Nullable[string] `json:"model,omitempty"`
	Name  string                    `json:"name"`

	// OwnerEmail SAML non-admins must use their session email; omission fills it, explicit null is forbidden. Full-access callers may use any owner or null.
	OwnerEmail nullable.Nullable[string] `json:"owner_email,omitempty"`

	// Profile Exact Orpheus profile name; creation uses the configured default when omitted.
	Profile *string `json:"profile,omitempty"`
	Prompt  string  `json:"prompt"`

	// Services Explicit selection of service codes. No defaults; empty clears the selection. Unknown codes return 422 and an unavailable catalog returns 503. Unchanged selections can be preserved without the catalog; resuming validates the full selection.
	Services    *ServiceCodes `json:"services,omitempty"`
	SessionMode *SessionMode  `json:"session_mode,omitempty"`
	Status      *Status       `json:"status,omitempty"`

	// Template Exact Orpheus template name; creation uses the configured default when omitted.
	Template *string `json:"template,omitempty"`
	Timezone string  `json:"timezone"`
}

// NullableOccurrence defines model for NullableOccurrence.
type NullableOccurrence struct {
	Attempts           int                                   `json:"attempts"`
	CreatedAt          time.Time                             `json:"created_at"`
	ErrorCode          nullable.Nullable[string]             `json:"error_code"`
	ExecutionStartedAt nullable.Nullable[time.Time]          `json:"execution_started_at"`
	FinishedAt         nullable.Nullable[time.Time]          `json:"finished_at"`
	ID                 openapi_types.UUID                    `json:"id"`
	NextAttemptAt      nullable.Nullable[time.Time]          `json:"next_attempt_at"`
	ObservedAt         nullable.Nullable[time.Time]          `json:"observed_at"`
	RunErrorCode       nullable.Nullable[string]             `json:"run_error_code"`
	RunID              nullable.Nullable[openapi_types.UUID] `json:"run_id"`
	RunStatus          nullable.Nullable[string]             `json:"run_status"`
	ScheduleID         openapi_types.UUID                    `json:"schedule_id"`
	ScheduledAt        time.Time                             `json:"scheduled_at"`
	SessionID          nullable.Nullable[openapi_types.UUID] `json:"session_id"`
	State              OccurrenceState                       `json:"state"`
	SyncErrorCode      nullable.Nullable[string]             `json:"sync_error_code"`
	UpdatedAt          time.Time                             `json:"updated_at"`
}

// Occurrence defines model for Occurrence.
type Occurrence struct {
	Attempts           int                                   `json:"attempts"`
	CreatedAt          time.Time                             `json:"created_at"`
	ErrorCode          nullable.Nullable[string]             `json:"error_code"`
	ExecutionStartedAt nullable.Nullable[time.Time]          `json:"execution_started_at"`
	FinishedAt         nullable.Nullable[time.Time]          `json:"finished_at"`
	ID                 openapi_types.UUID                    `json:"id"`
	NextAttemptAt      nullable.Nullable[time.Time]          `json:"next_attempt_at"`
	ObservedAt         nullable.Nullable[time.Time]          `json:"observed_at"`
	RunErrorCode       nullable.Nullable[string]             `json:"run_error_code"`
	RunID              nullable.Nullable[openapi_types.UUID] `json:"run_id"`
	RunStatus          nullable.Nullable[string]             `json:"run_status"`
	ScheduleID         openapi_types.UUID                    `json:"schedule_id"`
	ScheduledAt        time.Time                             `json:"scheduled_at"`
	SessionID          nullable.Nullable[openapi_types.UUID] `json:"session_id"`
	State              OccurrenceState                       `json:"state"`
	SyncErrorCode      nullable.Nullable[string]             `json:"sync_error_code"`
	UpdatedAt          time.Time                             `json:"updated_at"`
}

// OccurrencePage defines model for OccurrencePage.
type OccurrencePage struct {
	Items      []Occurrence              `json:"items"`
	NextCursor nullable.Nullable[string] `json:"next_cursor"`
}

// OccurrenceResult defines model for OccurrenceResult.
type OccurrenceResult struct {
	Error nullable.Nullable[struct {
		Code    string                    `json:"code"`
		Message string                    `json:"message"`
		Phase   nullable.Nullable[string] `json:"phase"`
	}] `json:"error"`
	FetchedAt    time.Time `json:"fetched_at"`
	FinalMessage nullable.Nullable[struct {
		CreatedAt time.Time          `json:"created_at"`
		ID        openapi_types.UUID `json:"id"`
		Text      string             `json:"text"`
	}] `json:"final_message"`
	RunStatus string `json:"run_status"`
}

// OccurrenceState defines model for OccurrenceState.
type OccurrenceState string

// Preview defines model for Preview.
type Preview struct {
	Times []time.Time `json:"times"`
}

// PreviewInput defines model for PreviewInput.
type PreviewInput struct {
	Cron     string `json:"cron"`
	Timezone string `json:"timezone"`
}

// Problem defines model for Problem.
type Problem struct {
	Error struct {
		Code    string `json:"code"`
		Details []struct {
			Code string   `json:"code"`
			Path []string `json:"path"`
		} `json:"details"`
		Message string                    `json:"message"`
		Phase   nullable.Nullable[string] `json:"phase"`
	} `json:"error"`
}

// Profile defines model for Profile.
type Profile struct {
	Codex        CodexProfile              `json:"codex"`
	Description  nullable.Nullable[string] `json:"description"`
	Harness      ProfileHarness            `json:"harness"`
	Instructions string                    `json:"instructions"`
	IsDefault    bool                      `json:"is_default"`
	Model        nullable.Nullable[string] `json:"model"`
	Name         string                    `json:"name"`
}

// ProfileHarness defines model for Profile.Harness.
type ProfileHarness string

// Profiles defines model for Profiles.
type Profiles struct {
	Items []Profile `json:"items"`
}

// Schedule defines model for Schedule.
type Schedule struct {
	// CanEdit Whether this caller may modify the current schedule. False for deleted schedules. Computed from current ownership even on an idempotent creation replay; busy state can still prevent session reset.
	CanEdit        bool                                  `json:"can_edit"`
	CreatedAt      time.Time                             `json:"created_at"`
	Cron           string                                `json:"cron"`
	DeletedAt      nullable.Nullable[time.Time]          `json:"deleted_at"`
	ID             openapi_types.UUID                    `json:"id"`
	LastOccurrence nullable.Nullable[NullableOccurrence] `json:"last_occurrence"`
	Model          nullable.Nullable[string]             `json:"model"`
	Name           string                                `json:"name"`
	NextRunAt      nullable.Nullable[time.Time]          `json:"next_run_at"`
	OwnerEmail     nullable.Nullable[string]             `json:"owner_email"`

	// Profile Stored Orpheus profile name.
	Profile string `json:"profile"`
	Prompt  string `json:"prompt"`

	// Services Explicit selection of service codes. No defaults; empty clears the selection. Unknown codes return 422 and an unavailable catalog returns 503. Unchanged selections can be preserved without the catalog; resuming validates the full selection.
	Services    ServiceCodes `json:"services"`
	SessionMode SessionMode  `json:"session_mode"`
	Status      Status       `json:"status"`

	// Template Stored Orpheus template name.
	Template  string    `json:"template"`
	Timezone  string    `json:"timezone"`
	UpdatedAt time.Time `json:"updated_at"`

	// URL Absolute Space Web card URL from ORPHEUS_PUBLIC_URL, or null when not configured. Computed at response time.
	URL nullable.Nullable[string] `json:"url"`
}

// SchedulePage defines model for SchedulePage.
type SchedulePage struct {
	Items      []Schedule                `json:"items"`
	NextCursor nullable.Nullable[string] `json:"next_cursor"`
}

// Service defines model for Service.
type Service struct {
	Code        string `json:"code"`
	Description string `json:"description"`

	// EnvFrom Names of worker environment variables included in this service; never values.
	EnvFrom []string `json:"env_from"`
	Name    string   `json:"name"`
}

// ServiceCodes Explicit selection of service codes. No defaults; empty clears the selection. Unknown codes return 422 and an unavailable catalog returns 503. Unchanged selections can be preserved without the catalog; resuming validates the full selection.
type ServiceCodes = []string

// Services defines model for Services.
type Services struct {
	Items []Service `json:"items"`
}

// SessionMode defines model for SessionMode.
type SessionMode string

// Settings defines model for Settings.
type Settings struct {
	BrowserAuth SettingsBrowserAuth `json:"browser_auth"`
}

// SettingsBrowserAuth defines model for Settings.BrowserAuth.
type SettingsBrowserAuth string

// Status defines model for Status.
type Status string

// Template defines model for Template.
type Template struct {
	Description nullable.Nullable[string] `json:"description"`
	IsDefault   bool                      `json:"is_default"`
	Name        string                    `json:"name"`
}

// Templates defines model for Templates.
type Templates struct {
	Items []Template `json:"items"`
}

// UpdateSchedule defines model for UpdateSchedule.
type UpdateSchedule struct {
	Cron       *string                   `json:"cron,omitempty"`
	Model      nullable.Nullable[string] `json:"model,omitempty"`
	Name       *string                   `json:"name,omitempty"`
	OwnerEmail nullable.Nullable[string] `json:"owner_email,omitempty"`

	// Profile Exact Orpheus profile name; omitted keeps the stored choice; a change starts a new reusable session.
	Profile *string `json:"profile,omitempty"`
	Prompt  *string `json:"prompt,omitempty"`

	// Services Explicit selection of service codes. No defaults; empty clears the selection. Unknown codes return 422 and an unavailable catalog returns 503. Unchanged selections can be preserved without the catalog; resuming validates the full selection.
	Services    *ServiceCodes `json:"services,omitempty"`
	SessionMode *SessionMode  `json:"session_mode,omitempty"`
	Status      *Status       `json:"status,omitempty"`

	// Template Exact Orpheus template name; omitted keeps the stored choice; a change starts a new reusable session.
	Template *string `json:"template,omitempty"`
	Timezone *string `json:"timezone,omitempty"`
}

// Cursor defines model for Cursor.
type Cursor = string

// ID defines model for ID.
type ID = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// OccurrenceID defines model for OccurrenceID.
type OccurrenceID = openapi_types.UUID

// OwnerEmail defines model for OwnerEmail.
type OwnerEmail = []string

// Unowned defines model for Unowned.
type Unowned = bool

// ListSchedulesParams defines parameters for ListSchedules.
type ListSchedulesParams struct {
	// OwnerEmail Repeated email filter; OR semantics, at most 100 distinct normalized emails.
	OwnerEmail *OwnerEmail `form:"owner_email,omitempty" json:"owner_email,omitempty"`

	// Unowned Only schedules without an owner. Cannot be combined with owner_email.
	Unowned *Unowned `form:"unowned,omitempty" json:"unowned,omitempty"`
	Status  *Status  `form:"status,omitempty" json:"status,omitempty"`
	Limit   *Limit   `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque position bound to normalized filters. New inserts are excluded from an ongoing traversal.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateScheduleParams defines parameters for CreateSchedule.
type CreateScheduleParams struct {
	// IdempotencyKey Retries with the same normalized body return the original response. Keys do not expire.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListOccurrencesParams defines parameters for ListOccurrences.
type ListOccurrencesParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque position bound to normalized filters. New inserts are excluded from an ongoing traversal.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// BrowserLoginParams defines parameters for BrowserLogin.
type BrowserLoginParams struct {
	Next *string `form:"next,omitempty" json:"next,omitempty"`
}

// CreateScheduleJSONRequestBody defines body for CreateSchedule for application/json ContentType.
type CreateScheduleJSONRequestBody = CreateSchedule

// PreviewScheduleJSONRequestBody defines body for PreviewSchedule for application/json ContentType.
type PreviewScheduleJSONRequestBody = PreviewInput

// UpdateScheduleJSONRequestBody defines body for UpdateSchedule for application/json ContentType.
type UpdateScheduleJSONRequestBody = UpdateSchedule

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetAuthSession Get browser access state
	// (GET /api/v1/auth/session)
	GetAuthSession(w http.ResponseWriter, r *http.Request)
	// GetProfiles Get Orpheus profiles and the creation default
	// (GET /api/v1/profiles)
	GetProfiles(w http.ResponseWriter, r *http.Request)
	// ListSchedules List schedules
	// (GET /api/v1/schedules)
	ListSchedules(w http.ResponseWriter, r *http.Request, params ListSchedulesParams)
	// CreateSchedule Create a schedule
	// (POST /api/v1/schedules)
	CreateSchedule(w http.ResponseWriter, r *http.Request, params CreateScheduleParams)
	// PreviewSchedule Preview five future cron occurrences
	// (POST /api/v1/schedules/preview)
	PreviewSchedule(w http.ResponseWriter, r *http.Request)
	// GetSettings Get schedule interface settings
	// (GET /api/v1/schedules/settings)
	GetSettings(w http.ResponseWriter, r *http.Request)
	// DeleteSchedule Soft delete a schedule
	// (DELETE /api/v1/schedules/{id})
	DeleteSchedule(w http.ResponseWriter, r *http.Request, id ID)
	// GetSchedule Get a schedule including deleted records
	// (GET /api/v1/schedules/{id})
	GetSchedule(w http.ResponseWriter, r *http.Request, id ID)
	// UpdateSchedule Update selected schedule fields
	// (PATCH /api/v1/schedules/{id})
	UpdateSchedule(w http.ResponseWriter, r *http.Request, id ID)
	// ListOccurrences Read stored history without calling the core
	// (GET /api/v1/schedules/{id}/occurrences)
	ListOccurrences(w http.ResponseWriter, r *http.Request, id ID, params ListOccurrencesParams)
	// GetOccurrence Read a stored occurrence without calling the core
	// (GET /api/v1/schedules/{id}/occurrences/{occurrence_id})
	GetOccurrence(w http.ResponseWriter, r *http.Request, id ID, occurrenceID OccurrenceID)
	// GetOccurrenceResult Explicitly fetch the current result from the Orpheus core
	// (GET /api/v1/schedules/{id}/occurrences/{occurrence_id}/result)
	GetOccurrenceResult(w http.ResponseWriter, r *http.Request, id ID, occurrenceID OccurrenceID)
	// ResetSession Detach the reusable session for the next occurrence
	// (POST /api/v1/schedules/{id}/reset-session)
	ResetSession(w http.ResponseWriter, r *http.Request, id ID)
	// GetServices Get available Orpheus services
	// (GET /api/v1/services)
	GetServices(w http.ResponseWriter, r *http.Request)
	// GetTemplates Get Orpheus templates and the creation default
	// (GET /api/v1/templates)
	GetTemplates(w http.ResponseWriter, r *http.Request)
	// BrowserCallback Consume a signed SAML HTTP-POST response
	// (POST /auth/callback)
	BrowserCallback(w http.ResponseWriter, r *http.Request)
	// BrowserLogin Start SP-initiated SAML login
	// (GET /auth/login)
	BrowserLogin(w http.ResponseWriter, r *http.Request, params BrowserLoginParams)
	// BrowserLogout Revoke the local browser session
	// (POST /auth/logout)
	BrowserLogout(w http.ResponseWriter, r *http.Request)
	// SamlMetadata Read service provider metadata
	// (GET /saml/metadata)
	SamlMetadata(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAuthSession operation middleware
func (siw *ServerInterfaceWrapper) GetAuthSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProfiles operation middleware
func (siw *ServerInterfaceWrapper) GetProfiles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProfiles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSchedules operation middleware
func (siw *ServerInterfaceWrapper) ListSchedules(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSchedulesParams

	// ------------- Optional query parameter "owner_email" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "owner_email", r.URL.Query(), &params.OwnerEmail, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "owner_email"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner_email", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "unowned" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "unowned", r.URL.Query(), &params.Unowned, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "unowned"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "unowned", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSchedules(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSchedule operation middleware
func (siw *ServerInterfaceWrapper) CreateSchedule(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateScheduleParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSchedule(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewSchedule operation middleware
func (siw *ServerInterfaceWrapper) PreviewSchedule(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewSchedule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSchedule operation middleware
func (siw *ServerInterfaceWrapper) DeleteSchedule(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSchedule operation middleware
func (siw *ServerInterfaceWrapper) GetSchedule(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSchedule operation middleware
func (siw *ServerInterfaceWrapper) UpdateSchedule(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOccurrences operation middleware
func (siw *ServerInterfaceWrapper) ListOccurrences(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOccurrencesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOccurrences(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOccurrence operation middleware
func (siw *ServerInterfaceWrapper) GetOccurrence(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "occurrence_id" -------------
	var occurrenceID OccurrenceID

	err = runtime.BindStyledParameterWithOptions("simple", "occurrence_id", r.PathValue("occurrence_id"), &occurrenceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "occurrence_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOccurrence(w, r, id, occurrenceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOccurrenceResult operation middleware
func (siw *ServerInterfaceWrapper) GetOccurrenceResult(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "occurrence_id" -------------
	var occurrenceID OccurrenceID

	err = runtime.BindStyledParameterWithOptions("simple", "occurrence_id", r.PathValue("occurrence_id"), &occurrenceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "occurrence_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOccurrenceResult(w, r, id, occurrenceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetSession operation middleware
func (siw *ServerInterfaceWrapper) ResetSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetSession(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetServices operation middleware
func (siw *ServerInterfaceWrapper) GetServices(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetServices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTemplates operation middleware
func (siw *ServerInterfaceWrapper) GetTemplates(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTemplates(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BrowserCallback operation middleware
func (siw *ServerInterfaceWrapper) BrowserCallback(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BrowserCallback(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BrowserLogin operation middleware
func (siw *ServerInterfaceWrapper) BrowserLogin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params BrowserLoginParams

	// ------------- Optional query parameter "next" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "next", r.URL.Query(), &params.Next, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "next"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "next", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BrowserLogin(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BrowserLogout operation middleware
func (siw *ServerInterfaceWrapper) BrowserLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BrowserLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SamlMetadata operation middleware
func (siw *ServerInterfaceWrapper) SamlMetadata(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SamlMetadata(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules", wrapper.ListSchedules)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/schedules", wrapper.CreateSchedule)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/schedules/{id}", wrapper.DeleteSchedule)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules/{id}", wrapper.GetSchedule)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/schedules/{id}", wrapper.UpdateSchedule)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/profiles", wrapper.GetProfiles)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/templates", wrapper.GetTemplates)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/services", wrapper.GetServices)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules/settings", wrapper.GetSettings)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/schedules/preview", wrapper.PreviewSchedule)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/auth/session", wrapper.GetAuthSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules/{id}/occurrences", wrapper.ListOccurrences)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules/{id}/occurrences/{occurrence_id}", wrapper.GetOccurrence)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules/{id}/occurrences/{occurrence_id}/result", wrapper.GetOccurrenceResult)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/schedules/{id}/reset-session", wrapper.ResetSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/login", wrapper.BrowserLogin)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/callback", wrapper.BrowserCallback)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.BrowserLogout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/saml/metadata", wrapper.SamlMetadata)

	return m
}

type ProblemJSONResponse Problem

type GetAuthSessionRequestObject struct {
}

type GetAuthSessionResponseObject interface {
	VisitGetAuthSessionResponse(w http.ResponseWriter) error
}

type GetAuthSession200JSONResponse AuthSession

func (response GetAuthSession200JSONResponse) VisitGetAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthSessiondefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetAuthSessiondefaultJSONResponse) VisitGetAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfilesRequestObject struct {
}

type GetProfilesResponseObject interface {
	VisitGetProfilesResponse(w http.ResponseWriter) error
}

type GetProfiles200JSONResponse Profiles

func (response GetProfiles200JSONResponse) VisitGetProfilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfilesdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetProfilesdefaultJSONResponse) VisitGetProfilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulesRequestObject struct {
	Params ListSchedulesParams
}

type ListSchedulesResponseObject interface {
	VisitListSchedulesResponse(w http.ResponseWriter) error
}

type ListSchedules200JSONResponse SchedulePage

func (response ListSchedules200JSONResponse) VisitListSchedulesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulesdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListSchedulesdefaultJSONResponse) VisitListSchedulesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateScheduleRequestObject struct {
	Params CreateScheduleParams
	Body   *CreateScheduleJSONRequestBody
}

type CreateScheduleResponseObject interface {
	VisitCreateScheduleResponse(w http.ResponseWriter) error
}

type CreateSchedule201JSONResponse Schedule

func (response CreateSchedule201JSONResponse) VisitCreateScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateScheduledefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateScheduledefaultJSONResponse) VisitCreateScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewScheduleRequestObject struct {
	Body *PreviewScheduleJSONRequestBody
}

type PreviewScheduleResponseObject interface {
	VisitPreviewScheduleResponse(w http.ResponseWriter) error
}

type PreviewSchedule200JSONResponse Preview

func (response PreviewSchedule200JSONResponse) VisitPreviewScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewScheduledefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PreviewScheduledefaultJSONResponse) VisitPreviewScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSettingsRequestObject struct {
}

type GetSettingsResponseObject interface {
	VisitGetSettingsResponse(w http.ResponseWriter) error
}

type GetSettings200JSONResponse Settings

func (response GetSettings200JSONResponse) VisitGetSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSettingsdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetSettingsdefaultJSONResponse) VisitGetSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteScheduleRequestObject struct {
	ID ID `json:"id"`
}

type DeleteScheduleResponseObject interface {
	VisitDeleteScheduleResponse(w http.ResponseWriter) error
}

type DeleteSchedule204Response struct {
}

func (response DeleteSchedule204Response) VisitDeleteScheduleResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteScheduledefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteScheduledefaultJSONResponse) VisitDeleteScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetScheduleRequestObject struct {
	ID ID `json:"id"`
}

type GetScheduleResponseObject interface {
	VisitGetScheduleResponse(w http.ResponseWriter) error
}

type GetSchedule200JSONResponse Schedule

func (response GetSchedule200JSONResponse) VisitGetScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetScheduledefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetScheduledefaultJSONResponse) VisitGetScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateScheduleRequestObject struct {
	ID   ID `json:"id"`
	Body *UpdateScheduleJSONRequestBody
}

type UpdateScheduleResponseObject interface {
	VisitUpdateScheduleResponse(w http.ResponseWriter) error
}

type UpdateSchedule200JSONResponse Schedule

func (response UpdateSchedule200JSONResponse) VisitUpdateScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateScheduledefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response UpdateScheduledefaultJSONResponse) VisitUpdateScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListOccurrencesRequestObject struct {
	ID     ID `json:"id"`
	Params ListOccurrencesParams
}

type ListOccurrencesResponseObject interface {
	VisitListOccurrencesResponse(w http.ResponseWriter) error
}

type ListOccurrences200JSONResponse OccurrencePage

func (response ListOccurrences200JSONResponse) VisitListOccurrencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOccurrencesdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListOccurrencesdefaultJSONResponse) VisitListOccurrencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetOccurrenceRequestObject struct {
	ID           ID           `json:"id"`
	OccurrenceID OccurrenceID `json:"occurrence_id"`
}

type GetOccurrenceResponseObject interface {
	VisitGetOccurrenceResponse(w http.ResponseWriter) error
}

type GetOccurrence200JSONResponse Occurrence

func (response GetOccurrence200JSONResponse) VisitGetOccurrenceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOccurrencedefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetOccurrencedefaultJSONResponse) VisitGetOccurrenceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetOccurrenceResultRequestObject struct {
	ID           ID           `json:"id"`
	OccurrenceID OccurrenceID `json:"occurrence_id"`
}

type GetOccurrenceResultResponseObject interface {
	VisitGetOccurrenceResultResponse(w http.ResponseWriter) error
}

type GetOccurrenceResult200JSONResponse OccurrenceResult

func (response GetOccurrenceResult200JSONResponse) VisitGetOccurrenceResultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOccurrenceResultdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetOccurrenceResultdefaultJSONResponse) VisitGetOccurrenceResultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ResetSessionRequestObject struct {
	ID ID `json:"id"`
}

type ResetSessionResponseObject interface {
	VisitResetSessionResponse(w http.ResponseWriter) error
}

type ResetSession200JSONResponse Schedule

func (response ResetSession200JSONResponse) VisitResetSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ResetSessiondefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ResetSessiondefaultJSONResponse) VisitResetSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetServicesRequestObject struct {
}

type GetServicesResponseObject interface {
	VisitGetServicesResponse(w http.ResponseWriter) error
}

type GetServices200JSONResponse Services

func (response GetServices200JSONResponse) VisitGetServicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetServicesdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetServicesdefaultJSONResponse) VisitGetServicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetTemplatesRequestObject struct {
}

type GetTemplatesResponseObject interface {
	VisitGetTemplatesResponse(w http.ResponseWriter) error
}

type GetTemplates200JSONResponse Templates

func (response GetTemplates200JSONResponse) VisitGetTemplatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTemplatesdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetTemplatesdefaultJSONResponse) VisitGetTemplatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type BrowserCallbackRequestObject struct {
}

type BrowserCallbackResponseObject interface {
	VisitBrowserCallbackResponse(w http.ResponseWriter) error
}

type BrowserCallback303ResponseHeaders struct {
	Location *string
}

type BrowserCallback303Response struct {
	Headers BrowserCallback303ResponseHeaders
}

func (response BrowserCallback303Response) VisitBrowserCallbackResponse(w http.ResponseWriter) error {
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(303)
	return nil
}

type BrowserCallbackdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response BrowserCallbackdefaultJSONResponse) VisitBrowserCallbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type BrowserLoginRequestObject struct {
	Params BrowserLoginParams
}

type BrowserLoginResponseObject interface {
	VisitBrowserLoginResponse(w http.ResponseWriter) error
}

type BrowserLogin302ResponseHeaders struct {
	Location *string
}

type BrowserLogin302Response struct {
	Headers BrowserLogin302ResponseHeaders
}

func (response BrowserLogin302Response) VisitBrowserLoginResponse(w http.ResponseWriter) error {
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(302)
	return nil
}

type BrowserLogindefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response BrowserLogindefaultJSONResponse) VisitBrowserLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type BrowserLogoutRequestObject struct {
}

type BrowserLogoutResponseObject interface {
	VisitBrowserLogoutResponse(w http.ResponseWriter) error
}

type BrowserLogout204Response struct {
}

func (response BrowserLogout204Response) VisitBrowserLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type BrowserLogoutdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response BrowserLogoutdefaultJSONResponse) VisitBrowserLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SamlMetadataRequestObject struct {
}

type SamlMetadataResponseObject interface {
	VisitSamlMetadataResponse(w http.ResponseWriter) error
}

type SamlMetadata200ApplicationSamlmetadataXMLResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response SamlMetadata200ApplicationSamlmetadataXMLResponse) VisitSamlMetadataResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/samlmetadata+xml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type SamlMetadatadefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response SamlMetadatadefaultJSONResponse) VisitSamlMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetAuthSession Get browser access state
	// (GET /api/v1/auth/session)
	GetAuthSession(ctx context.Context, request GetAuthSessionRequestObject) (GetAuthSessionResponseObject, error)
	// GetProfiles Get Orpheus profiles and the creation default
	// (GET /api/v1/profiles)
	GetProfiles(ctx context.Context, request GetProfilesRequestObject) (GetProfilesResponseObject, error)
	// ListSchedules List schedules
	// (GET /api/v1/schedules)
	ListSchedules(ctx context.Context, request ListSchedulesRequestObject) (ListSchedulesResponseObject, error)
	// CreateSchedule Create a schedule
	// (POST /api/v1/schedules)
	CreateSchedule(ctx context.Context, request CreateScheduleRequestObject) (CreateScheduleResponseObject, error)
	// PreviewSchedule Preview five future cron occurrences
	// (POST /api/v1/schedules/preview)
	PreviewSchedule(ctx context.Context, request PreviewScheduleRequestObject) (PreviewScheduleResponseObject, error)
	// GetSettings Get schedule interface settings
	// (GET /api/v1/schedules/settings)
	GetSettings(ctx context.Context, request GetSettingsRequestObject) (GetSettingsResponseObject, error)
	// DeleteSchedule Soft delete a schedule
	// (DELETE /api/v1/schedules/{id})
	DeleteSchedule(ctx context.Context, request DeleteScheduleRequestObject) (DeleteScheduleResponseObject, error)
	// GetSchedule Get a schedule including deleted records
	// (GET /api/v1/schedules/{id})
	GetSchedule(ctx context.Context, request GetScheduleRequestObject) (GetScheduleResponseObject, error)
	// UpdateSchedule Update selected schedule fields
	// (PATCH /api/v1/schedules/{id})
	UpdateSchedule(ctx context.Context, request UpdateScheduleRequestObject) (UpdateScheduleResponseObject, error)
	// ListOccurrences Read stored history without calling the core
	// (GET /api/v1/schedules/{id}/occurrences)
	ListOccurrences(ctx context.Context, request ListOccurrencesRequestObject) (ListOccurrencesResponseObject, error)
	// GetOccurrence Read a stored occurrence without calling the core
	// (GET /api/v1/schedules/{id}/occurrences/{occurrence_id})
	GetOccurrence(ctx context.Context, request GetOccurrenceRequestObject) (GetOccurrenceResponseObject, error)
	// GetOccurrenceResult Explicitly fetch the current result from the Orpheus core
	// (GET /api/v1/schedules/{id}/occurrences/{occurrence_id}/result)
	GetOccurrenceResult(ctx context.Context, request GetOccurrenceResultRequestObject) (GetOccurrenceResultResponseObject, error)
	// ResetSession Detach the reusable session for the next occurrence
	// (POST /api/v1/schedules/{id}/reset-session)
	ResetSession(ctx context.Context, request ResetSessionRequestObject) (ResetSessionResponseObject, error)
	// GetServices Get available Orpheus services
	// (GET /api/v1/services)
	GetServices(ctx context.Context, request GetServicesRequestObject) (GetServicesResponseObject, error)
	// GetTemplates Get Orpheus templates and the creation default
	// (GET /api/v1/templates)
	GetTemplates(ctx context.Context, request GetTemplatesRequestObject) (GetTemplatesResponseObject, error)
	// BrowserCallback Consume a signed SAML HTTP-POST response
	// (POST /auth/callback)
	BrowserCallback(ctx context.Context, request BrowserCallbackRequestObject) (BrowserCallbackResponseObject, error)
	// BrowserLogin Start SP-initiated SAML login
	// (GET /auth/login)
	BrowserLogin(ctx context.Context, request BrowserLoginRequestObject) (BrowserLoginResponseObject, error)
	// BrowserLogout Revoke the local browser session
	// (POST /auth/logout)
	BrowserLogout(ctx context.Context, request BrowserLogoutRequestObject) (BrowserLogoutResponseObject, error)
	// SamlMetadata Read service provider metadata
	// (GET /saml/metadata)
	SamlMetadata(ctx context.Context, request SamlMetadataRequestObject) (SamlMetadataResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAuthSession operation middleware
func (sh *strictHandler) GetAuthSession(w http.ResponseWriter, r *http.Request) {
	var request GetAuthSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthSession(ctx, request.(GetAuthSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthSessionResponseObject); ok {
		if err := validResponse.VisitGetAuthSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProfiles operation middleware
func (sh *strictHandler) GetProfiles(w http.ResponseWriter, r *http.Request) {
	var request GetProfilesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProfiles(ctx, request.(GetProfilesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProfiles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProfilesResponseObject); ok {
		if err := validResponse.VisitGetProfilesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSchedules operation middleware
func (sh *strictHandler) ListSchedules(w http.ResponseWriter, r *http.Request, params ListSchedulesParams) {
	var request ListSchedulesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSchedules(ctx, request.(ListSchedulesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSchedules")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSchedulesResponseObject); ok {
		if err := validResponse.VisitListSchedulesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSchedule operation middleware
func (sh *strictHandler) CreateSchedule(w http.ResponseWriter, r *http.Request, params CreateScheduleParams) {
	var request CreateScheduleRequestObject

	request.Params = params

	var body CreateScheduleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSchedule(ctx, request.(CreateScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateScheduleResponseObject); ok {
		if err := validResponse.VisitCreateScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PreviewSchedule operation middleware
func (sh *strictHandler) PreviewSchedule(w http.ResponseWriter, r *http.Request) {
	var request PreviewScheduleRequestObject

	var body PreviewScheduleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PreviewSchedule(ctx, request.(PreviewScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PreviewSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PreviewScheduleResponseObject); ok {
		if err := validResponse.VisitPreviewScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSettings operation middleware
func (sh *strictHandler) GetSettings(w http.ResponseWriter, r *http.Request) {
	var request GetSettingsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSettings(ctx, request.(GetSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSettings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSettingsResponseObject); ok {
		if err := validResponse.VisitGetSettingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSchedule operation middleware
func (sh *strictHandler) DeleteSchedule(w http.ResponseWriter, r *http.Request, id ID) {
	var request DeleteScheduleRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSchedule(ctx, request.(DeleteScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteScheduleResponseObject); ok {
		if err := validResponse.VisitDeleteScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSchedule operation middleware
func (sh *strictHandler) GetSchedule(w http.ResponseWriter, r *http.Request, id ID) {
	var request GetScheduleRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSchedule(ctx, request.(GetScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetScheduleResponseObject); ok {
		if err := validResponse.VisitGetScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSchedule operation middleware
func (sh *strictHandler) UpdateSchedule(w http.ResponseWriter, r *http.Request, id ID) {
	var request UpdateScheduleRequestObject

	request.ID = id

	var body UpdateScheduleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSchedule(ctx, request.(UpdateScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateScheduleResponseObject); ok {
		if err := validResponse.VisitUpdateScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOccurrences operation middleware
func (sh *strictHandler) ListOccurrences(w http.ResponseWriter, r *http.Request, id ID, params ListOccurrencesParams) {
	var request ListOccurrencesRequestObject

	request.ID = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOccurrences(ctx, request.(ListOccurrencesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOccurrences")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOccurrencesResponseObject); ok {
		if err := validResponse.VisitListOccurrencesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOccurrence operation middleware
func (sh *strictHandler) GetOccurrence(w http.ResponseWriter, r *http.Request, id ID, occurrenceID OccurrenceID) {
	var request GetOccurrenceRequestObject

	request.ID = id
	request.OccurrenceID = occurrenceID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOccurrence(ctx, request.(GetOccurrenceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOccurrence")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOccurrenceResponseObject); ok {
		if err := validResponse.VisitGetOccurrenceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOccurrenceResult operation middleware
func (sh *strictHandler) GetOccurrenceResult(w http.ResponseWriter, r *http.Request, id ID, occurrenceID OccurrenceID) {
	var request GetOccurrenceResultRequestObject

	request.ID = id
	request.OccurrenceID = occurrenceID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOccurrenceResult(ctx, request.(GetOccurrenceResultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOccurrenceResult")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOccurrenceResultResponseObject); ok {
		if err := validResponse.VisitGetOccurrenceResultResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResetSession operation middleware
func (sh *strictHandler) ResetSession(w http.ResponseWriter, r *http.Request, id ID) {
	var request ResetSessionRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResetSession(ctx, request.(ResetSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResetSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResetSessionResponseObject); ok {
		if err := validResponse.VisitResetSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetServices operation middleware
func (sh *strictHandler) GetServices(w http.ResponseWriter, r *http.Request) {
	var request GetServicesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetServices(ctx, request.(GetServicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetServices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetServicesResponseObject); ok {
		if err := validResponse.VisitGetServicesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTemplates operation middleware
func (sh *strictHandler) GetTemplates(w http.ResponseWriter, r *http.Request) {
	var request GetTemplatesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTemplates(ctx, request.(GetTemplatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTemplates")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTemplatesResponseObject); ok {
		if err := validResponse.VisitGetTemplatesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BrowserCallback operation middleware
func (sh *strictHandler) BrowserCallback(w http.ResponseWriter, r *http.Request) {
	var request BrowserCallbackRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BrowserCallback(ctx, request.(BrowserCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BrowserCallback")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BrowserCallbackResponseObject); ok {
		if err := validResponse.VisitBrowserCallbackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BrowserLogin operation middleware
func (sh *strictHandler) BrowserLogin(w http.ResponseWriter, r *http.Request, params BrowserLoginParams) {
	var request BrowserLoginRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BrowserLogin(ctx, request.(BrowserLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BrowserLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BrowserLoginResponseObject); ok {
		if err := validResponse.VisitBrowserLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BrowserLogout operation middleware
func (sh *strictHandler) BrowserLogout(w http.ResponseWriter, r *http.Request) {
	var request BrowserLogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BrowserLogout(ctx, request.(BrowserLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BrowserLogout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BrowserLogoutResponseObject); ok {
		if err := validResponse.VisitBrowserLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SamlMetadata operation middleware
func (sh *strictHandler) SamlMetadata(w http.ResponseWriter, r *http.Request) {
	var request SamlMetadataRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SamlMetadata(ctx, request.(SamlMetadataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SamlMetadata")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SamlMetadataResponseObject); ok {
		if err := validResponse.VisitSamlMetadataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7DxZbxs5mn+FqJ2HBFuW5KMX3fZTrt42xmkbdjKzQOAVqKpPEjssskKyZKsD//fFx6MulaSSbXl6B3np",
	"jly8vvskv0eJzHIpQBgdnX6PcqpoBgaU/fWuUFoq/FcKOlEsN0yK6DS6zOm3AkguNcO/kIksREqMJEKq",
	"jHL2J6RkyjguMyC/wx1hQoMymlAFBO4TXqQ4QsmMUEGkmEkmZsQougClKR9EccRwn28FqGUUR4JmEJ1G",
	"iTtOHOlkDhnFc2X0/gLEzMyj058PfzmKo4yJ8IfDODLLHCdqo5iYRQ8PcXT+HqfZ1XNq5tXiLI3iSMG3",
	"gilIo1OjCqhvNEXITHQaFYUd2bFyClkuDYhk+XdYriLtGoxioMkdM3Ni5kA0zaCOsYlMl0SBKZSw36Vi",
	"MyYoJwp0LoWGAfk7LDVJEc+GwH3OFJS4mgNNQVXw1I5zgOfZDZgLljFTYqpFB24/1hdMYUoLbqLTn0Yx",
	"0oRlRRadHo1GliDuV0UOJgzMQNmNLpOkUApEAmspI8sh4ycT6fJOgPqQUca7CJQDNZASwO+egc/I5TXR",
	"kFFhWKJjQg3JpDbkcDQiKdOGicTUiWjnaqQK3OdcphBO2YVIiacZ2ykNdDIDmRXAFgAlRFQpusTf2iw5",
	"/gEhx983hppCryOcdl/rW/1NwTQ6jf5jWOmBofuqh34xxNtngWdNO1SB4EuCE9KCe+aWhbFijcANyDsq",
	"kFsnQBKZTZiA1ElADfZ18l74Tevn9QiYSMmBiugBDxfkw8J9peSEQ4b/TKQwICwb0zznLKF46OEfGk/+",
	"vScSwnp2pybsN0YViSkUpOTN1TkBpaQakJPRIUkUpCAMo1zH5GR0TN7dXP9KpCoxNZ5KNWFpCgK/n5CM",
	"ac3EDH/8QhIpppwlJiYnR0dkQTlL7clj8tPomBSCLijjdMJhYGnjT4qAvCnM/Aa0Zg5CmqZWQVN+pWQO",
	"yjDE0ZRyDXGU1/70PaKFmeOJE5SALkTHUULFOKOCzmBMeYf8vKOCuO+Ecl5jCipSQrVmM4EoSDhQhQqO",
	"KccEekA+qQLIFD9KMWUzi9KbNx8vCE0zJnTskEDeAlWgyFdY+kWFFMtMFppkMrWqcPXUTk3qMTUNDZFS",
	"AweGZYDsVnCLziCqK1KXWTn+HoFARfYlojkbS8GRVcsjRHGkacaj2475Cmg6pkkCWnejttCgthKsfcwm",
	"AVOmc06XYyc7HaoDurXe7y3d5cwy2h9LAGb52CxjJB2egNzNQTSZsAcGdTH5AxLTcbCHukL/Ug6MmwCF",
	"41fYlW7cQxzdKWaght5VrkwUUAMtjsxkyqZLYuZSAymhQS/GzJkmCeUc9ZfFAtKnodwcqhKn2+wBuriv",
	"BZtlo7glak3uaEGzInSeVRps3YWTdzKF+yslp4zDjpoAplOpTJ3dhRQQeUtO8Qxc3uFvSFmRRXE0ZzM0",
	"1/f+/xm9x3Nyo2inNOSgNJ6EmWXHLlPFQKRWtnJFZxk1LOlcRoNasATGhjnZ2ej5IQdmGVWNHWlhJKJY",
	"ioRp3DsFQxm3RLGnue1yIVZxbbnrxjPXjthOlBQ9To+sw1fHbZW7oA1qfnLwyjZtV3dMViTKSoSQ4sAp",
	"Z5IV2qCEeJ2unf1xInJGpDVtUqA/xTVhJkbPlbOEGadPmCalMRyQXwvODxz3exHUJKNLuz4VS2cxgi4a",
	"RPGuCMkrmWhC9eGeJoZcqnwOhSZ+GEH8nTn9gTAUGrTVjTU75X1fpxdlxoyBdPVgXQfJctOHcR2f663e",
	"mhuHkq/dPIv3cTBem+fasR9xKE4tvcg+7mEcGchyTs1WrIZxe0QrmvQ/UXa3Ibalm72V8VSJnVzWlutS",
	"sr97ZqtimCfacGoQQy4SL+Om0WrchMezocomr2YFNdY/HSeeHbZKCtxDUiAgY22o2rLZ1tWmTDA9f+Ii",
	"LO0R5cWRgHsz9rh80n5ygsL3xEOrQox3RD1O6Ya119RKfLcOL+ORnqgN43fjvKCKHgkTwrNVhVVCeGOH",
	"47ylSHZFfZGnOwpWS5GwNKrQNG78sqsGcBoy3Ni3ga+SGRqkbbLmGlltCt0KI67ip6Ei4kobrUpUlzbc",
	"QQv+0Ho/tN4PrfdD6/1bab0rOttV85V53vIf/WjdlQm2h03Kgs0WkrfJZ/dvLrIZ2mvQNuG/E7wW0U/0",
	"kQNPr4bIoDWddX/L51TD7mjxLBFWDut0YWYKJpnvqCCmWN0Z1879FLQ8wjT21H4G7nsk7txcHNqQ8S5c",
	"NbX15mUb4l9DspfaqI3FzVx7E3RqSAHlIFLc1qUbqUnm7hdNEshdek5/ZXlu/zUNyaGEigQ4/rsrMXWl",
	"YMHgbkfZQCI1dUE/Imb0/tzN+MkGx9WPpoZo4dVt14Utf/xzkRdmP8msx8bofWLyWvnn2RVTT0XksohN",
	"Wj7HurYqukN1sIU9X1S1y3dhrm1QXk6fVihbPVdrBUeoNYR/RLIbT3S/zfA2kuntKmAP72pOlfC1iaB3",
	"3L5d2oMJbcuKTIpuIjM9LsvtXbWkMlXcOzncKzNWB7oCKWwXe4ha52+cdgPV9F4dpxrpNkqIW6zrmI9N",
	"7lMxhtQ1UjSYJvrnHMwcVL3UZNPcZVEKiLNZpqxaDcivuIctk6bAwUBaftMD8k5meWFCW02Y7Aqsc5YT",
	"WAC22mDxioXWEFOlYBVgse2MTAq9JNZXx+oW0YZxTnKFs02Z2legwXSXWx/jh/Q0Gx7ol4ilOdVmLBsJ",
	"jU0M1pEIfvmajfXd0V16UuzfLPw8V3HlxkgFaWd15UeppBtHjVrJcxY+HhPtx1GhOiqBbyZa8sIAuclp",
	"AuSfMCEJVSn5fH3h1NDl9dVvHz7fjK8+v704fzf+fH3R6iPA8nlV9KlpMWrKtjdimMNAJbaKbWfmrvgE",
	"oYgrtRxvLfvEVc9UMHSByWu0bHFQ3G7sCmy5KftRF9+GrlvVRpss1N6zEGGjf1kOwgvvI73qnBoDCpn3",
	"f7/Qgz9v8T+jg1/GB7ffR/F/HT/8Leq0PA2Hb+U7iMUY+b2ju4ZmoImckjupvoIiIBZMSZGhNV1QxRA9",
	"mjDhW2KZcB6B55gzImABCrufCrBNhf07A/s5d94j7/TxSqg2UMGp0I6yr6/wa+BgfUHEgYeK4KbYGCxD",
	"kVefEchys3S9Ya4UXM4ckM/iK3YCunmhQxZb41wPWL0ZiSTUUC5nfpTGjjlcIJlTMYO0WlVb92YCJFfg",
	"cople4+Zl8ucEQW6yLA72bfh+UL1FDVYdcQ6ZR7FYQ3qxVEh2LcCfCiPwlNhfL+ust/kKa5yzT7Wu3vg",
	"LsIlCg2dYc8NGMPEbFfoJkreaVBj7Kl6fIdeC7jGop0wlka/3C8xbGEtCS30mrzQp5rp3wHEXaPNbfHh",
	"E6K+LcFcAHC/LFqi8fE8+tka3n/njq2X6IryTTnkK0DudbZzYZO5tMaLEqd2iS3PaEKJgDuCOsCqau8z",
	"/QgA+vRKvRyyd8nOribrNCSFYmaJwuUT2hOgCtQbr6EtRqxKsn+ujOHcmBz399q31sZu7wYkUn5lUF0O",
	"GI9/k9ocSIeuscYIZOyhrBalOcPLL7Z5n4mp7Ai7vBbwrevWM0O/wqN3zvAfS7zH4BwL/KZs8YuASHPJ",
	"hNFEAa0iNywwzpUUstB8eea6g3XpP1iyeEGKKyrbLb1/VDkpSC7OEhA+2+pA/3j+yccyDmv6dDiUOQgt",
	"C5XAQKrZ0E8aZszldplB6Y7CEV289ubqPIqjBSiH6Gg0OByMcDguRnMWnUbHg9HgOHK5Z0vMIc3ZcHE4",
	"RNs41BWNZmDlExWlTSidp9Fp9N9g6jcSWjc1jkajZ7ulUd+m66ZG4fqp7YfSNnYtWJ6wdvGj4uro9Mtt",
	"rZUYASSeX4lvWg11bkPRmflir2REt7hIQF1ey3muQ1uZF90jzso99oGwBopa9sP131s3O6QfwyYV3ry8",
	"6SbuyoTnWuRdMG1uylFx40bjl24QqiHD2v2wh3jr6HArqsfQ0gBsHemu3vUY6G9nPtzukUcaaYW98gnS",
	"rcpn1xihIuYtugJSm+0t6Ul16QOjAJszL28chc50WvYV+65y7ERnnIccuotCndkkHxo961Lh3SObwXdT",
	"Q7iJd71W73gN/M2luHZjycau7rRzuvARpdMhqPWbTN26YrArV7eupjqO+VaANm9lunw2Zmmd8qHpkPsw",
	"tsWqh8/OqvtlUwcjoSWV13Bql84a5lVnQODjJp197b1G6H3QqVHh70Wl0XPvvV8i+U3IlFnBMoVCU4NJ",
	"qDKJqnehm64lJ9ZZ7DKBsU9tHPbYu8UOsBMmDKgptV5pCWBvxH1n6YPT1hwM9NPbbqzT25XOrlU634Ng",
	"kAa/OqQDuxXviiZ9b1dvCFiDWCcdh3w2zN7IqQnwbdUg8XpWW3v60f8zbYqsRuvMhnlwzLaGAreCRKp0",
	"gzuwmx18b22f7fPqx4yuRLOWGa0V97dAffhdv+Ec7sA/iWNbyar9mITWJi9sFF6G2RyMPrquNU+QKQOe",
	"7qzXhnVjsikauWwYnd049i8VDLR6nfdKrGug7RxMWaDBfhlUEu7GoILn1A69yD383niT5GGTX1AhLXoR",
	"0rwAWWggTIWFl6DNdiFoPCbzSFoOVdnZvp2kvgv+RQjr99oreUOUiyEzmGTeaETzWc8yNg5Znb8umRVo",
	"MAe1LOXj3IXeKQe7374812tc/AVSqS9jjN+DoZ6/2jWKkK0h2AlS0zE9DHSt/OOFt9WwZKv2bpB9jKzx",
	"7gcsQC1DN6Z9pMjm9X1Shlz7HM+H3/9hizI6XmnP6IgKy9af/REs7LF/V73EVlnrqODbnLg19drwOsVa",
	"FZD3iK5qkxfLe5fAPybxjYUW5MkJTb7WM0cd6iiTqYtVBgSjA0xo1vF0f3B3d3eAXXQHheIgEpmG17gA",
	"a498SaRw7/5ce+jsga+B06W9OlN7/4x8ZG8H5FK4lkHigxI7PlREhETPgCr3ldkGv89CS2tibHDnUejH",
	"/GH98lU5euvWexeQ0GKO49Fxx7M/Uugis2E2m4nwnNRvnz5dHVxd3nwq945i/3KeXepCOlStrvcPX75L",
	"CZeJfZPPKm+siw26Higri6QPTVba95tk58I9lcXljAnfyP3qZDR6HRPmP1lMBPjx4+HrmNQeJbJsyaxK",
	"TvHzyeuYSFsltO86SpWRVyeHx69tK2dz3lAbqegMGi1Zr34aHb8ebKyj9aZWJRIWwLWKvikOZ8Tm6u+Y",
	"BvvaGi4wFtKMQVgoB87U2IdsJngKR2Ma2luRyuQVBvk4kyhZGNCvz4Lwkq6iqO1vwxI1YilX8n5JHKMR",
	"owpt1nL5hYVrxXHqeh9PuNt2na9hHo1Ofl6t2N+uiM5RB+4MVYbcXB0wwQyzPG/Ryf3JesmLnXGeXmEv",
	"8F9SQGoCHARkiwwEFVc9yEfcjUDy6uTo6DnFYTMFGjIgC7PeKFw7tbvyts6lfVnU6ur/OfBG6sA+UehZ",
	"FL4VlKNLdDggZfHInNX7M10/xoC8l6BtG7cBlTGB+gY/I+lrPSfrWB2P3ycHew0L+dWt7GQz2Bgdiv7/",
	"EiZyT7Qi4evYe3Uy8trxkfTfDi2ygKYZH2ZgaEoNXetW3dCMfwyDdnKrcP2w/H/eZ7yJuRUxjldIRquW",
	"llzJBUPclOd9WYK92WLeqoPtTqvNYLbmNtuhvtxiuNvueLJ/RV2NywYDULX7nA6HlivmUpvTn0eHIxul",
	"evdxRQ/PqapfFIvLOo7LXWNVzJclB5VlqeKrh7i94psSO6GdI245uGWE5e6AOP1SW730cFcXf9tspgnP",
	"evqJFmkPtw//NwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
