//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthSessionMode.
const (
	AuthSessionModeAPIOnly   AuthSessionMode = "api_only"
	AuthSessionModeAnonymous AuthSessionMode = "anonymous"
)

// Valid indicates whether the value is a known member of the AuthSessionMode enum.
func (e AuthSessionMode) Valid() bool {
	switch e {
	case AuthSessionModeAPIOnly:
		return true
	case AuthSessionModeAnonymous:
		return true
	default:
		return false
	}
}

// Defines values for NullableOccurrenceState.
const (
	NullableOccurrenceStateAccepted    NullableOccurrenceState = "accepted"
	NullableOccurrenceStateCancelled   NullableOccurrenceState = "cancelled"
	NullableOccurrenceStateDispatching NullableOccurrenceState = "dispatching"
	NullableOccurrenceStateFailed      NullableOccurrenceState = "failed"
	NullableOccurrenceStatePending     NullableOccurrenceState = "pending"
	NullableOccurrenceStateSkipped     NullableOccurrenceState = "skipped"
)

// Valid indicates whether the value is a known member of the NullableOccurrenceState enum.
func (e NullableOccurrenceState) Valid() bool {
	switch e {
	case NullableOccurrenceStateAccepted:
		return true
	case NullableOccurrenceStateCancelled:
		return true
	case NullableOccurrenceStateDispatching:
		return true
	case NullableOccurrenceStateFailed:
		return true
	case NullableOccurrenceStatePending:
		return true
	case NullableOccurrenceStateSkipped:
		return true
	default:
		return false
	}
}

// Defines values for OccurrenceState.
const (
	OccurrenceStateAccepted    OccurrenceState = "accepted"
	OccurrenceStateCancelled   OccurrenceState = "cancelled"
	OccurrenceStateDispatching OccurrenceState = "dispatching"
	OccurrenceStateFailed      OccurrenceState = "failed"
	OccurrenceStatePending     OccurrenceState = "pending"
	OccurrenceStateSkipped     OccurrenceState = "skipped"
)

// Valid indicates whether the value is a known member of the OccurrenceState enum.
func (e OccurrenceState) Valid() bool {
	switch e {
	case OccurrenceStateAccepted:
		return true
	case OccurrenceStateCancelled:
		return true
	case OccurrenceStateDispatching:
		return true
	case OccurrenceStateFailed:
		return true
	case OccurrenceStatePending:
		return true
	case OccurrenceStateSkipped:
		return true
	default:
		return false
	}
}

// Defines values for SessionMode.
const (
	New   SessionMode = "new"
	Reuse SessionMode = "reuse"
)

// Valid indicates whether the value is a known member of the SessionMode enum.
func (e SessionMode) Valid() bool {
	switch e {
	case New:
		return true
	case Reuse:
		return true
	default:
		return false
	}
}

// Defines values for SettingsBrowserAuth.
const (
	SettingsBrowserAuthAPIOnly   SettingsBrowserAuth = "api_only"
	SettingsBrowserAuthAnonymous SettingsBrowserAuth = "anonymous"
)

// Valid indicates whether the value is a known member of the SettingsBrowserAuth enum.
func (e SettingsBrowserAuth) Valid() bool {
	switch e {
	case SettingsBrowserAuthAPIOnly:
		return true
	case SettingsBrowserAuthAnonymous:
		return true
	default:
		return false
	}
}

// Defines values for Status.
const (
	Active Status = "active"
	Paused Status = "paused"
)

// Valid indicates whether the value is a known member of the Status enum.
func (e Status) Valid() bool {
	switch e {
	case Active:
		return true
	case Paused:
		return true
	default:
		return false
	}
}

// AuthSession defines model for AuthSession.
type AuthSession struct {
	Authenticated bool                                      `json:"authenticated"`
	ExpiresAt     nullable.Nullable[time.Time]              `json:"expires_at"`
	Mode          AuthSessionMode                           `json:"mode"`
	ReadAccess    bool                                      `json:"read_access"`
	User          nullable.Nullable[map[string]interface{}] `json:"user"`
	WriteAccess   bool                                      `json:"write_access"`
}

// AuthSessionMode defines model for AuthSession.Mode.
type AuthSessionMode string

// CreateSchedule defines model for CreateSchedule.
type CreateSchedule struct {
	Cron        string                    `json:"cron"`
	EnvFrom     *EnvFrom                  `json:"env_from,omitempty"`
	Model       nullable.Nullable[string] `json:"model,omitempty"`
	Name        string                    `json:"name"`
	OwnerEmail  nullable.Nullable[string] `json:"owner_email,omitempty"`
	Prompt      string                    `json:"prompt"`
	SessionMode *SessionMode              `json:"session_mode,omitempty"`
	Status      *Status                   `json:"status,omitempty"`
	Timezone    string                    `json:"timezone"`
}

// EnvFrom defines model for EnvFrom.
type EnvFrom = []string

// NullableOccurrence defines model for NullableOccurrence.
type NullableOccurrence struct {
	Attempts           int                                   `json:"attempts"`
	CreatedAt          time.Time                             `json:"created_at"`
	ErrorCode          nullable.Nullable[string]             `json:"error_code"`
	ExecutionStartedAt nullable.Nullable[time.Time]          `json:"execution_started_at"`
	FinishedAt         nullable.Nullable[time.Time]          `json:"finished_at"`
	ID                 openapi_types.UUID                    `json:"id"`
	NextAttemptAt      nullable.Nullable[time.Time]          `json:"next_attempt_at"`
	ObservedAt         nullable.Nullable[time.Time]          `json:"observed_at"`
	RunErrorCode       nullable.Nullable[string]             `json:"run_error_code"`
	RunID              nullable.Nullable[openapi_types.UUID] `json:"run_id"`
	RunStatus          nullable.Nullable[string]             `json:"run_status"`
	ScheduleID         openapi_types.UUID                    `json:"schedule_id"`
	ScheduledAt        time.Time                             `json:"scheduled_at"`
	SessionID          nullable.Nullable[openapi_types.UUID] `json:"session_id"`
	State              NullableOccurrenceState               `json:"state"`
	SyncErrorCode      nullable.Nullable[string]             `json:"sync_error_code"`
	UpdatedAt          time.Time                             `json:"updated_at"`
}

// NullableOccurrenceState defines model for NullableOccurrence.State.
type NullableOccurrenceState string

// Occurrence defines model for Occurrence.
type Occurrence struct {
	Attempts           int                                   `json:"attempts"`
	CreatedAt          time.Time                             `json:"created_at"`
	ErrorCode          nullable.Nullable[string]             `json:"error_code"`
	ExecutionStartedAt nullable.Nullable[time.Time]          `json:"execution_started_at"`
	FinishedAt         nullable.Nullable[time.Time]          `json:"finished_at"`
	ID                 openapi_types.UUID                    `json:"id"`
	NextAttemptAt      nullable.Nullable[time.Time]          `json:"next_attempt_at"`
	ObservedAt         nullable.Nullable[time.Time]          `json:"observed_at"`
	RunErrorCode       nullable.Nullable[string]             `json:"run_error_code"`
	RunID              nullable.Nullable[openapi_types.UUID] `json:"run_id"`
	RunStatus          nullable.Nullable[string]             `json:"run_status"`
	ScheduleID         openapi_types.UUID                    `json:"schedule_id"`
	ScheduledAt        time.Time                             `json:"scheduled_at"`
	SessionID          nullable.Nullable[openapi_types.UUID] `json:"session_id"`
	State              OccurrenceState                       `json:"state"`
	SyncErrorCode      nullable.Nullable[string]             `json:"sync_error_code"`
	UpdatedAt          time.Time                             `json:"updated_at"`
}

// OccurrenceState defines model for Occurrence.State.
type OccurrenceState string

// OccurrencePage defines model for OccurrencePage.
type OccurrencePage struct {
	Items      []Occurrence              `json:"items"`
	NextCursor nullable.Nullable[string] `json:"next_cursor"`
}

// OccurrenceResult defines model for OccurrenceResult.
type OccurrenceResult struct {
	Error nullable.Nullable[struct {
		Code    string                    `json:"code"`
		Message string                    `json:"message"`
		Phase   nullable.Nullable[string] `json:"phase"`
	}] `json:"error"`
	FetchedAt    time.Time `json:"fetched_at"`
	FinalMessage nullable.Nullable[struct {
		CreatedAt time.Time          `json:"created_at"`
		ID        openapi_types.UUID `json:"id"`
		Text      string             `json:"text"`
	}] `json:"final_message"`
	RunStatus string `json:"run_status"`
}

// Preview defines model for Preview.
type Preview struct {
	Times []time.Time `json:"times"`
}

// PreviewInput defines model for PreviewInput.
type PreviewInput struct {
	Cron     string `json:"cron"`
	Timezone string `json:"timezone"`
}

// Problem defines model for Problem.
type Problem struct {
	Error struct {
		Code    string `json:"code"`
		Details []struct {
			Code string   `json:"code"`
			Path []string `json:"path"`
		} `json:"details"`
		Message string                    `json:"message"`
		Phase   nullable.Nullable[string] `json:"phase"`
	} `json:"error"`
}

// Schedule defines model for Schedule.
type Schedule struct {
	CreatedAt      time.Time                             `json:"created_at"`
	Cron           string                                `json:"cron"`
	DeletedAt      nullable.Nullable[time.Time]          `json:"deleted_at"`
	EnvFrom        EnvFrom                               `json:"env_from"`
	ID             openapi_types.UUID                    `json:"id"`
	LastOccurrence nullable.Nullable[NullableOccurrence] `json:"last_occurrence"`
	Model          nullable.Nullable[string]             `json:"model"`
	Name           string                                `json:"name"`
	NextRunAt      nullable.Nullable[time.Time]          `json:"next_run_at"`
	OwnerEmail     nullable.Nullable[string]             `json:"owner_email"`
	Prompt         string                                `json:"prompt"`
	SessionMode    SessionMode                           `json:"session_mode"`
	Status         Status                                `json:"status"`
	Timezone       string                                `json:"timezone"`
	UpdatedAt      time.Time                             `json:"updated_at"`
}

// SchedulePage defines model for SchedulePage.
type SchedulePage struct {
	Items      []Schedule                `json:"items"`
	NextCursor nullable.Nullable[string] `json:"next_cursor"`
}

// SessionMode defines model for SessionMode.
type SessionMode string

// Settings defines model for Settings.
type Settings struct {
	AllowedEnvFrom EnvFrom             `json:"allowed_env_from"`
	BaseEnvFrom    EnvFrom             `json:"base_env_from"`
	BrowserAuth    SettingsBrowserAuth `json:"browser_auth"`
}

// SettingsBrowserAuth defines model for Settings.BrowserAuth.
type SettingsBrowserAuth string

// Status defines model for Status.
type Status string

// UpdateSchedule defines model for UpdateSchedule.
type UpdateSchedule struct {
	Cron        *string                   `json:"cron,omitempty"`
	EnvFrom     *EnvFrom                  `json:"env_from,omitempty"`
	Model       nullable.Nullable[string] `json:"model,omitempty"`
	Name        *string                   `json:"name,omitempty"`
	OwnerEmail  nullable.Nullable[string] `json:"owner_email,omitempty"`
	Prompt      *string                   `json:"prompt,omitempty"`
	SessionMode *SessionMode              `json:"session_mode,omitempty"`
	Status      *Status                   `json:"status,omitempty"`
	Timezone    *string                   `json:"timezone,omitempty"`
}

// Cursor defines model for Cursor.
type Cursor = string

// ID defines model for ID.
type ID = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// OccurrenceID defines model for OccurrenceID.
type OccurrenceID = openapi_types.UUID

// OwnerEmail defines model for OwnerEmail.
type OwnerEmail = []string

// Unowned defines model for Unowned.
type Unowned = bool

// ListSchedulesParams defines parameters for ListSchedules.
type ListSchedulesParams struct {
	// OwnerEmail Repeated email filter; OR semantics, at most 100 distinct normalized emails.
	OwnerEmail *OwnerEmail `form:"owner_email,omitempty" json:"owner_email,omitempty"`

	// Unowned Only schedules without an owner. Cannot be combined with owner_email.
	Unowned *Unowned `form:"unowned,omitempty" json:"unowned,omitempty"`
	Status  *Status  `form:"status,omitempty" json:"status,omitempty"`
	Limit   *Limit   `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque position bound to normalized filters. New inserts are excluded from an ongoing traversal.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateScheduleParams defines parameters for CreateSchedule.
type CreateScheduleParams struct {
	// IdempotencyKey Retries with the same normalized body return the original response. Keys do not expire.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListOccurrencesParams defines parameters for ListOccurrences.
type ListOccurrencesParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque position bound to normalized filters. New inserts are excluded from an ongoing traversal.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateScheduleJSONRequestBody defines body for CreateSchedule for application/json ContentType.
type CreateScheduleJSONRequestBody = CreateSchedule

// PreviewScheduleJSONRequestBody defines body for PreviewSchedule for application/json ContentType.
type PreviewScheduleJSONRequestBody = PreviewInput

// UpdateScheduleJSONRequestBody defines body for UpdateSchedule for application/json ContentType.
type UpdateScheduleJSONRequestBody = UpdateSchedule

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetAuthSession Get browser access state
	// (GET /api/v1/auth/session)
	GetAuthSession(w http.ResponseWriter, r *http.Request)
	// ListSchedules List schedules
	// (GET /api/v1/schedules)
	ListSchedules(w http.ResponseWriter, r *http.Request, params ListSchedulesParams)
	// CreateSchedule Create a schedule
	// (POST /api/v1/schedules)
	CreateSchedule(w http.ResponseWriter, r *http.Request, params CreateScheduleParams)
	// PreviewSchedule Preview five future cron occurrences
	// (POST /api/v1/schedules/preview)
	PreviewSchedule(w http.ResponseWriter, r *http.Request)
	// GetSettings Get allowed environment names
	// (GET /api/v1/schedules/settings)
	GetSettings(w http.ResponseWriter, r *http.Request)
	// DeleteSchedule Soft delete a schedule
	// (DELETE /api/v1/schedules/{id})
	DeleteSchedule(w http.ResponseWriter, r *http.Request, id ID)
	// GetSchedule Get a schedule including deleted records
	// (GET /api/v1/schedules/{id})
	GetSchedule(w http.ResponseWriter, r *http.Request, id ID)
	// UpdateSchedule Update selected schedule fields
	// (PATCH /api/v1/schedules/{id})
	UpdateSchedule(w http.ResponseWriter, r *http.Request, id ID)
	// ListOccurrences Read stored history without calling the core
	// (GET /api/v1/schedules/{id}/occurrences)
	ListOccurrences(w http.ResponseWriter, r *http.Request, id ID, params ListOccurrencesParams)
	// GetOccurrence Read a stored occurrence without calling the core
	// (GET /api/v1/schedules/{id}/occurrences/{occurrence_id})
	GetOccurrence(w http.ResponseWriter, r *http.Request, id ID, occurrenceID OccurrenceID)
	// GetOccurrenceResult Explicitly fetch the current result from the Orpheus core
	// (GET /api/v1/schedules/{id}/occurrences/{occurrence_id}/result)
	GetOccurrenceResult(w http.ResponseWriter, r *http.Request, id ID, occurrenceID OccurrenceID)
	// ResetSession Detach the reusable session for the next occurrence
	// (POST /api/v1/schedules/{id}/reset-session)
	ResetSession(w http.ResponseWriter, r *http.Request, id ID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAuthSession operation middleware
func (siw *ServerInterfaceWrapper) GetAuthSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSchedules operation middleware
func (siw *ServerInterfaceWrapper) ListSchedules(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSchedulesParams

	// ------------- Optional query parameter "owner_email" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "owner_email", r.URL.Query(), &params.OwnerEmail, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "owner_email"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner_email", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "unowned" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "unowned", r.URL.Query(), &params.Unowned, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "unowned"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "unowned", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSchedules(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSchedule operation middleware
func (siw *ServerInterfaceWrapper) CreateSchedule(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateScheduleParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSchedule(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewSchedule operation middleware
func (siw *ServerInterfaceWrapper) PreviewSchedule(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewSchedule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSchedule operation middleware
func (siw *ServerInterfaceWrapper) DeleteSchedule(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSchedule operation middleware
func (siw *ServerInterfaceWrapper) GetSchedule(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSchedule operation middleware
func (siw *ServerInterfaceWrapper) UpdateSchedule(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOccurrences operation middleware
func (siw *ServerInterfaceWrapper) ListOccurrences(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOccurrencesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOccurrences(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOccurrence operation middleware
func (siw *ServerInterfaceWrapper) GetOccurrence(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "occurrence_id" -------------
	var occurrenceID OccurrenceID

	err = runtime.BindStyledParameterWithOptions("simple", "occurrence_id", r.PathValue("occurrence_id"), &occurrenceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "occurrence_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOccurrence(w, r, id, occurrenceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOccurrenceResult operation middleware
func (siw *ServerInterfaceWrapper) GetOccurrenceResult(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "occurrence_id" -------------
	var occurrenceID OccurrenceID

	err = runtime.BindStyledParameterWithOptions("simple", "occurrence_id", r.PathValue("occurrence_id"), &occurrenceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "occurrence_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOccurrenceResult(w, r, id, occurrenceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetSession operation middleware
func (siw *ServerInterfaceWrapper) ResetSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetSession(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules", wrapper.ListSchedules)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/schedules", wrapper.CreateSchedule)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/schedules/{id}", wrapper.DeleteSchedule)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules/{id}", wrapper.GetSchedule)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/schedules/{id}", wrapper.UpdateSchedule)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules/settings", wrapper.GetSettings)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/schedules/preview", wrapper.PreviewSchedule)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/auth/session", wrapper.GetAuthSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules/{id}/occurrences", wrapper.ListOccurrences)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules/{id}/occurrences/{occurrence_id}", wrapper.GetOccurrence)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules/{id}/occurrences/{occurrence_id}/result", wrapper.GetOccurrenceResult)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/schedules/{id}/reset-session", wrapper.ResetSession)

	return m
}

type ProblemJSONResponse Problem

type GetAuthSessionRequestObject struct {
}

type GetAuthSessionResponseObject interface {
	VisitGetAuthSessionResponse(w http.ResponseWriter) error
}

type GetAuthSession200JSONResponse AuthSession

func (response GetAuthSession200JSONResponse) VisitGetAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthSessiondefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetAuthSessiondefaultJSONResponse) VisitGetAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulesRequestObject struct {
	Params ListSchedulesParams
}

type ListSchedulesResponseObject interface {
	VisitListSchedulesResponse(w http.ResponseWriter) error
}

type ListSchedules200JSONResponse SchedulePage

func (response ListSchedules200JSONResponse) VisitListSchedulesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulesdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListSchedulesdefaultJSONResponse) VisitListSchedulesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateScheduleRequestObject struct {
	Params CreateScheduleParams
	Body   *CreateScheduleJSONRequestBody
}

type CreateScheduleResponseObject interface {
	VisitCreateScheduleResponse(w http.ResponseWriter) error
}

type CreateSchedule201JSONResponse Schedule

func (response CreateSchedule201JSONResponse) VisitCreateScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateScheduledefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateScheduledefaultJSONResponse) VisitCreateScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewScheduleRequestObject struct {
	Body *PreviewScheduleJSONRequestBody
}

type PreviewScheduleResponseObject interface {
	VisitPreviewScheduleResponse(w http.ResponseWriter) error
}

type PreviewSchedule200JSONResponse Preview

func (response PreviewSchedule200JSONResponse) VisitPreviewScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewScheduledefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PreviewScheduledefaultJSONResponse) VisitPreviewScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSettingsRequestObject struct {
}

type GetSettingsResponseObject interface {
	VisitGetSettingsResponse(w http.ResponseWriter) error
}

type GetSettings200JSONResponse Settings

func (response GetSettings200JSONResponse) VisitGetSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSettingsdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetSettingsdefaultJSONResponse) VisitGetSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteScheduleRequestObject struct {
	ID ID `json:"id"`
}

type DeleteScheduleResponseObject interface {
	VisitDeleteScheduleResponse(w http.ResponseWriter) error
}

type DeleteSchedule204Response struct {
}

func (response DeleteSchedule204Response) VisitDeleteScheduleResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteScheduledefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteScheduledefaultJSONResponse) VisitDeleteScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetScheduleRequestObject struct {
	ID ID `json:"id"`
}

type GetScheduleResponseObject interface {
	VisitGetScheduleResponse(w http.ResponseWriter) error
}

type GetSchedule200JSONResponse Schedule

func (response GetSchedule200JSONResponse) VisitGetScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetScheduledefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetScheduledefaultJSONResponse) VisitGetScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateScheduleRequestObject struct {
	ID   ID `json:"id"`
	Body *UpdateScheduleJSONRequestBody
}

type UpdateScheduleResponseObject interface {
	VisitUpdateScheduleResponse(w http.ResponseWriter) error
}

type UpdateSchedule200JSONResponse Schedule

func (response UpdateSchedule200JSONResponse) VisitUpdateScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateScheduledefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response UpdateScheduledefaultJSONResponse) VisitUpdateScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListOccurrencesRequestObject struct {
	ID     ID `json:"id"`
	Params ListOccurrencesParams
}

type ListOccurrencesResponseObject interface {
	VisitListOccurrencesResponse(w http.ResponseWriter) error
}

type ListOccurrences200JSONResponse OccurrencePage

func (response ListOccurrences200JSONResponse) VisitListOccurrencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOccurrencesdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListOccurrencesdefaultJSONResponse) VisitListOccurrencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetOccurrenceRequestObject struct {
	ID           ID           `json:"id"`
	OccurrenceID OccurrenceID `json:"occurrence_id"`
}

type GetOccurrenceResponseObject interface {
	VisitGetOccurrenceResponse(w http.ResponseWriter) error
}

type GetOccurrence200JSONResponse Occurrence

func (response GetOccurrence200JSONResponse) VisitGetOccurrenceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOccurrencedefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetOccurrencedefaultJSONResponse) VisitGetOccurrenceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetOccurrenceResultRequestObject struct {
	ID           ID           `json:"id"`
	OccurrenceID OccurrenceID `json:"occurrence_id"`
}

type GetOccurrenceResultResponseObject interface {
	VisitGetOccurrenceResultResponse(w http.ResponseWriter) error
}

type GetOccurrenceResult200JSONResponse OccurrenceResult

func (response GetOccurrenceResult200JSONResponse) VisitGetOccurrenceResultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOccurrenceResultdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetOccurrenceResultdefaultJSONResponse) VisitGetOccurrenceResultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ResetSessionRequestObject struct {
	ID ID `json:"id"`
}

type ResetSessionResponseObject interface {
	VisitResetSessionResponse(w http.ResponseWriter) error
}

type ResetSession200JSONResponse Schedule

func (response ResetSession200JSONResponse) VisitResetSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ResetSessiondefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ResetSessiondefaultJSONResponse) VisitResetSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetAuthSession Get browser access state
	// (GET /api/v1/auth/session)
	GetAuthSession(ctx context.Context, request GetAuthSessionRequestObject) (GetAuthSessionResponseObject, error)
	// ListSchedules List schedules
	// (GET /api/v1/schedules)
	ListSchedules(ctx context.Context, request ListSchedulesRequestObject) (ListSchedulesResponseObject, error)
	// CreateSchedule Create a schedule
	// (POST /api/v1/schedules)
	CreateSchedule(ctx context.Context, request CreateScheduleRequestObject) (CreateScheduleResponseObject, error)
	// PreviewSchedule Preview five future cron occurrences
	// (POST /api/v1/schedules/preview)
	PreviewSchedule(ctx context.Context, request PreviewScheduleRequestObject) (PreviewScheduleResponseObject, error)
	// GetSettings Get allowed environment names
	// (GET /api/v1/schedules/settings)
	GetSettings(ctx context.Context, request GetSettingsRequestObject) (GetSettingsResponseObject, error)
	// DeleteSchedule Soft delete a schedule
	// (DELETE /api/v1/schedules/{id})
	DeleteSchedule(ctx context.Context, request DeleteScheduleRequestObject) (DeleteScheduleResponseObject, error)
	// GetSchedule Get a schedule including deleted records
	// (GET /api/v1/schedules/{id})
	GetSchedule(ctx context.Context, request GetScheduleRequestObject) (GetScheduleResponseObject, error)
	// UpdateSchedule Update selected schedule fields
	// (PATCH /api/v1/schedules/{id})
	UpdateSchedule(ctx context.Context, request UpdateScheduleRequestObject) (UpdateScheduleResponseObject, error)
	// ListOccurrences Read stored history without calling the core
	// (GET /api/v1/schedules/{id}/occurrences)
	ListOccurrences(ctx context.Context, request ListOccurrencesRequestObject) (ListOccurrencesResponseObject, error)
	// GetOccurrence Read a stored occurrence without calling the core
	// (GET /api/v1/schedules/{id}/occurrences/{occurrence_id})
	GetOccurrence(ctx context.Context, request GetOccurrenceRequestObject) (GetOccurrenceResponseObject, error)
	// GetOccurrenceResult Explicitly fetch the current result from the Orpheus core
	// (GET /api/v1/schedules/{id}/occurrences/{occurrence_id}/result)
	GetOccurrenceResult(ctx context.Context, request GetOccurrenceResultRequestObject) (GetOccurrenceResultResponseObject, error)
	// ResetSession Detach the reusable session for the next occurrence
	// (POST /api/v1/schedules/{id}/reset-session)
	ResetSession(ctx context.Context, request ResetSessionRequestObject) (ResetSessionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAuthSession operation middleware
func (sh *strictHandler) GetAuthSession(w http.ResponseWriter, r *http.Request) {
	var request GetAuthSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthSession(ctx, request.(GetAuthSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthSessionResponseObject); ok {
		if err := validResponse.VisitGetAuthSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSchedules operation middleware
func (sh *strictHandler) ListSchedules(w http.ResponseWriter, r *http.Request, params ListSchedulesParams) {
	var request ListSchedulesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSchedules(ctx, request.(ListSchedulesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSchedules")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSchedulesResponseObject); ok {
		if err := validResponse.VisitListSchedulesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSchedule operation middleware
func (sh *strictHandler) CreateSchedule(w http.ResponseWriter, r *http.Request, params CreateScheduleParams) {
	var request CreateScheduleRequestObject

	request.Params = params

	var body CreateScheduleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSchedule(ctx, request.(CreateScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateScheduleResponseObject); ok {
		if err := validResponse.VisitCreateScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PreviewSchedule operation middleware
func (sh *strictHandler) PreviewSchedule(w http.ResponseWriter, r *http.Request) {
	var request PreviewScheduleRequestObject

	var body PreviewScheduleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PreviewSchedule(ctx, request.(PreviewScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PreviewSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PreviewScheduleResponseObject); ok {
		if err := validResponse.VisitPreviewScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSettings operation middleware
func (sh *strictHandler) GetSettings(w http.ResponseWriter, r *http.Request) {
	var request GetSettingsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSettings(ctx, request.(GetSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSettings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSettingsResponseObject); ok {
		if err := validResponse.VisitGetSettingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSchedule operation middleware
func (sh *strictHandler) DeleteSchedule(w http.ResponseWriter, r *http.Request, id ID) {
	var request DeleteScheduleRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSchedule(ctx, request.(DeleteScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteScheduleResponseObject); ok {
		if err := validResponse.VisitDeleteScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSchedule operation middleware
func (sh *strictHandler) GetSchedule(w http.ResponseWriter, r *http.Request, id ID) {
	var request GetScheduleRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSchedule(ctx, request.(GetScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetScheduleResponseObject); ok {
		if err := validResponse.VisitGetScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSchedule operation middleware
func (sh *strictHandler) UpdateSchedule(w http.ResponseWriter, r *http.Request, id ID) {
	var request UpdateScheduleRequestObject

	request.ID = id

	var body UpdateScheduleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSchedule(ctx, request.(UpdateScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateScheduleResponseObject); ok {
		if err := validResponse.VisitUpdateScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOccurrences operation middleware
func (sh *strictHandler) ListOccurrences(w http.ResponseWriter, r *http.Request, id ID, params ListOccurrencesParams) {
	var request ListOccurrencesRequestObject

	request.ID = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOccurrences(ctx, request.(ListOccurrencesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOccurrences")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOccurrencesResponseObject); ok {
		if err := validResponse.VisitListOccurrencesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOccurrence operation middleware
func (sh *strictHandler) GetOccurrence(w http.ResponseWriter, r *http.Request, id ID, occurrenceID OccurrenceID) {
	var request GetOccurrenceRequestObject

	request.ID = id
	request.OccurrenceID = occurrenceID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOccurrence(ctx, request.(GetOccurrenceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOccurrence")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOccurrenceResponseObject); ok {
		if err := validResponse.VisitGetOccurrenceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOccurrenceResult operation middleware
func (sh *strictHandler) GetOccurrenceResult(w http.ResponseWriter, r *http.Request, id ID, occurrenceID OccurrenceID) {
	var request GetOccurrenceResultRequestObject

	request.ID = id
	request.OccurrenceID = occurrenceID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOccurrenceResult(ctx, request.(GetOccurrenceResultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOccurrenceResult")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOccurrenceResultResponseObject); ok {
		if err := validResponse.VisitGetOccurrenceResultResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResetSession operation middleware
func (sh *strictHandler) ResetSession(w http.ResponseWriter, r *http.Request, id ID) {
	var request ResetSessionRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResetSession(ctx, request.(ResetSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResetSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResetSessionResponseObject); ok {
		if err := validResponse.VisitResetSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FtZbyM3Ev4rBDdPi7YkzwFktE+TmcnCyCQe2JuXNbwCxS5JzLLJHh6yNYb++6LYd6t1tG1pE4zfutUk",
	"6/iqisVi6YFynaRagXKWjh9oygxLwIEJbx+8sdrgUwyWG5E6oRUd08uUffVAUm0F/kKm2quYOE2UNgmT",
	"4hvEZCYkLjMgv8EdEcqCcZYwAwTuufQxjjA6IUwRreZaqDlxhi3BWCYHNKIC6Xz1YFY0ooolQMeUZ+xE",
	"1PIFJAz5Stj9Z1Bzt6DjH8/fvYpoIlTxw3lE3SrFidYZoeZ0vY7oxUecFlZPmVtUi4uYRtTAVy8MxHTs",
	"jIc6oRlK5uiYeh9GdqwcQ5JqB4qvfoHVptKuwBkBltwJtyBuAcSyBOoam+p4RQw4b1T4ro2YC8UkMWBT",
	"rSwMyC+wsiRGPTsC96kwUOpqASwGU8lTY+cM+eknzGeRCFdqqoWDDB/rC8YwY146On47ihATkfiEjl+N",
	"RgGQ7K2CQygHczCB0CXn3hhQHLYio8shkyeDdHmnwHxKmJBdAKXAHMQE8HtuwP8gl1fEQsKUE9xGhDmS",
	"aOvI+WhEYmGdUNzVQQxzLaIC96nUMRRcdilSIzeTMKWhTuEgCQ7YEqCUiBnDVvhu3UriDyg5vl875rzd",
	"BpzNvtZJ/WBgRsf0b8MqDgyzr3aYL4Z6+10hr3FHKFByRXBC7GVu3Nq74NYo3IB8YAqtdQqE62QqFMSZ",
	"B9Rk3+bvPida5zdXwFRrCUzRNTJX+EeQ+4vRUwkJPnKtHKhgxixNpeAMmR7+YZHzhwOVUKwXKDVlv3bG",
	"c+cNxOT9lwsCxmgzIG9G54QbiEE5waSNyJvRa/Lh+upnfHpDEmGtUHN8eUe4VjMpuIvIm1evyJJJEQce",
	"I/J29Jp4xZZMSDaVMAgo5Dwhy++9W1yDtSKThcVxCMVMfjE6BeMEWDqeMWkhomntpwfKvFsgbxxtvUul",
	"wXSFATthruFVMXNw5kQCCJGXgbHCvDcsNQm2/0BBofPfUJaKiVYS4WVKq1WivaW3HRMNsHjCOAdru7nz",
	"Fsxembfwp6d/AHe4yp0RDnbQWdcDzU0mTtRSXpPZ1po5ow1t3nYw8sEAc3Cdu1BPMLnJ8N+57UUU1HKC",
	"2+0+Y/+klj/jsBw/ubn0Xtwz323szMU+sIvDeijsTzQ1OkndAYqwmctMCuvcGf6ysb/iUJxahtZDYmZE",
	"0VG+aQV7uWpZWlBgKVKUQVxbrsuGCtzqe0fKnAOj6Jj+5+b92b/Z2bfJbf4wOns3uf37DzTas8FE1Cvx",
	"1cNFtiYqfx3R33I0qq27tze2IpJzkKRZAlqmC6PNdAF1EXboXYFp0/YxLE94DvheU4J74B4FmVjHzB5i",
	"e1ebCSXs4omLiPiA5CaiCu7dJNflk+jpqQWzfCLTxqtJT9XjlG5ZD5paOeje4UXCMjlQtcX4fpZXBJtH",
	"yoTyNLbQFFSM3yIaC5syxxfZG244abYf2f+KNA1PMyZkeOBMcZD43LXb2pXifXHyadzTC1shTsS00umk",
	"8RZWLWRvOHyDbkO5peU07KBpx1scu+mhG1a7qZ9GPImq0LXpfl1xukfIfAmRLyHyJUS+hMjvN0R+YfO+",
	"YbJMfsuHXbl6RaqrtBKY5WUFdA/kbfgC/eYiu6W9AhsqaL3kDYp+YvZd2PTmCR6sZfPub+mCWeivltwk",
	"ipWLdbo0MwPHFz2jyQzLpZMa309RyyP20QNDpYN716HVrggQhjZ8vEtXzdC+e9mG+9eUnHstbWuxi94X",
	"A0sBdz2NFbXWdM7DtJqw+/wA+jaUEaqXpsu2BM3I7WD/QqXeHafe8tiz/yFn/VqB89kjxYGRIQaHVe4G",
	"ls+xbqj796h/t7SXXxuE5bs0147wpwtwlco2+WqtkAHVxf6jS4T9A9mBZh6DhKem/48oTR4YZiWzbqIb",
	"J65dBDrKWqcvg4Z8AUP0kw4n328t9bky731F2Ki6S8sspKWOqHW3V1r5rny9Dn7DuTZteVd8OHreXBD6",
	"v2XNdWuqHf4U3FFc0DdSyso0rsE5oeZ9tysmpb6DePKISDVlFh41z+g7C2aC102PuERrqbXJRbQpUItg",
	"p8pLjy154U4sg5Mwb7ccnX8P5v1yt/U9321tpjsWuDfCrdAu8iPBFJgB8z4390AQJ2U/VyF74Vya3cQL",
	"NdOb3QiFpZGEKTaHBBS2IsTEOo239AuBD6sBCV0L2GODTRqCC0dMOH4TUHGqhcJ3Ftsw5NKkC/CWcG2A",
	"YK1jYbTS3soV9i1IwUHlmWKwDvrrxb9oRL2ROb92PBzqFJTV3nAYaDMf5pOGicjyUuEQf1pQuk4ZB2wp",
	"oBHFjqhMttHgfDAK5pSCYqmgY/p6MBq8plneHNQ4ZKkYLs+H6MZDW7UHzCEYEHpX6C+4iOmY/hNcvYug",
	"1UfxajR6th6KOpmuPgqf3Zivo6qRqHvBksNaW0ZlT3R8cxtR65OEmVUmIMkDG8ku5UlRNHMMt4Gb0EZB",
	"b3GRQnVlL8tWvX0W1l2Xo6JGz9xNN9/VkGGtA2kd7R1d9N0cMLT0zr0js+auAwbm/X/r2yPaRiNrOYZx",
	"lOaAuFWtSjUjqMC8xXirbQforS6Nvqi3mgMzjX71YN1POl49mzJbXK6bmUB+f9+C8vzZoTwujJmMhJVQ",
	"bkGyy6eHaVW56sY5rw3VgD4GTo0K1EEojZ6b9nFByomQmVgCmXnnDRDM50h1hrF9cLO11H3bZlam98eM",
	"VgWNo2oPN648SSeglsJoFVIZzDB6qe1BxOssS5LgYFNrH8PvDWNvKO5NR4r1bFJe65kjGWf7vTnaDvtW",
	"7kd/scgWYC8VQYTCRnnsjM9LAcQA1ybesXX125M+hn0o3JJuarZ1dDtOHGwROXEkPA2qmYzEggSOIJb4",
	"zgTIuLc7D+sRdFeKetmItP1M40+VIbZuhI8K1hWw9mmx7GnnTEr0RjwUcm3gOd3wILiHD42/Qqx3bYaV",
	"0uhJoDkBLKwAptLCKbDZ7wSN/7A8EsuhKe//90Oa9wqcBNic1lHh/ZRXYeSKhBvpDMbAQFmZCf8Wa9dj",
	"/pwwG7Dgzmrll8fty53nkytc+wQlm9PsjR/BsRxuA95iHZTkeiMzbcIHvAyoufy2/bJZB2pWFG9u19ED",
	"6jQ0O+UoVBW68XAoNWdyoa0b/zg6HwX951Q28t8FM7Vd3EakOJuESmM45OSnzEH1V6aK1XXUXvGnZokq",
	"0THUZgYJ1rfr/w0A",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
