//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthSessionMode.
const (
	AuthSessionModeAPIOnly   AuthSessionMode = "api_only"
	AuthSessionModeAnonymous AuthSessionMode = "anonymous"
	AuthSessionModeSaml      AuthSessionMode = "saml"
)

// Valid indicates whether the value is a known member of the AuthSessionMode enum.
func (e AuthSessionMode) Valid() bool {
	switch e {
	case AuthSessionModeAPIOnly:
		return true
	case AuthSessionModeAnonymous:
		return true
	case AuthSessionModeSaml:
		return true
	default:
		return false
	}
}

// Defines values for CodexProfileEffort.
const (
	CodexProfileEffortHigh    CodexProfileEffort = "high"
	CodexProfileEffortLow     CodexProfileEffort = "low"
	CodexProfileEffortMax     CodexProfileEffort = "max"
	CodexProfileEffortMedium  CodexProfileEffort = "medium"
	CodexProfileEffortMinimal CodexProfileEffort = "minimal"
	CodexProfileEffortNone    CodexProfileEffort = "none"
	CodexProfileEffortUltra   CodexProfileEffort = "ultra"
	CodexProfileEffortXhigh   CodexProfileEffort = "xhigh"
)

// Valid indicates whether the value is a known member of the CodexProfileEffort enum.
func (e CodexProfileEffort) Valid() bool {
	switch e {
	case CodexProfileEffortHigh:
		return true
	case CodexProfileEffortLow:
		return true
	case CodexProfileEffortMax:
		return true
	case CodexProfileEffortMedium:
		return true
	case CodexProfileEffortMinimal:
		return true
	case CodexProfileEffortNone:
		return true
	case CodexProfileEffortUltra:
		return true
	case CodexProfileEffortXhigh:
		return true
	default:
		return false
	}
}

// Defines values for CodexProfilePersonality.
const (
	CodexProfilePersonalityFriendly  CodexProfilePersonality = "friendly"
	CodexProfilePersonalityNone      CodexProfilePersonality = "none"
	CodexProfilePersonalityPragmatic CodexProfilePersonality = "pragmatic"
)

// Valid indicates whether the value is a known member of the CodexProfilePersonality enum.
func (e CodexProfilePersonality) Valid() bool {
	switch e {
	case CodexProfilePersonalityFriendly:
		return true
	case CodexProfilePersonalityNone:
		return true
	case CodexProfilePersonalityPragmatic:
		return true
	default:
		return false
	}
}

// Defines values for CodexProfileSummary.
const (
	CodexProfileSummaryAuto     CodexProfileSummary = "auto"
	CodexProfileSummaryConcise  CodexProfileSummary = "concise"
	CodexProfileSummaryDetailed CodexProfileSummary = "detailed"
	CodexProfileSummaryNone     CodexProfileSummary = "none"
)

// Valid indicates whether the value is a known member of the CodexProfileSummary enum.
func (e CodexProfileSummary) Valid() bool {
	switch e {
	case CodexProfileSummaryAuto:
		return true
	case CodexProfileSummaryConcise:
		return true
	case CodexProfileSummaryDetailed:
		return true
	case CodexProfileSummaryNone:
		return true
	default:
		return false
	}
}

// Defines values for OccurrenceState.
const (
	Accepted    OccurrenceState = "accepted"
	Cancelled   OccurrenceState = "cancelled"
	Dispatching OccurrenceState = "dispatching"
	Failed      OccurrenceState = "failed"
	Pending     OccurrenceState = "pending"
	Skipped     OccurrenceState = "skipped"
)

// Valid indicates whether the value is a known member of the OccurrenceState enum.
func (e OccurrenceState) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Cancelled:
		return true
	case Dispatching:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Skipped:
		return true
	default:
		return false
	}
}

// Defines values for ProfileHarness.
const (
	Codex ProfileHarness = "codex"
)

// Valid indicates whether the value is a known member of the ProfileHarness enum.
func (e ProfileHarness) Valid() bool {
	switch e {
	case Codex:
		return true
	default:
		return false
	}
}

// Defines values for SessionMode.
const (
	New   SessionMode = "new"
	Reuse SessionMode = "reuse"
)

// Valid indicates whether the value is a known member of the SessionMode enum.
func (e SessionMode) Valid() bool {
	switch e {
	case New:
		return true
	case Reuse:
		return true
	default:
		return false
	}
}

// Defines values for SettingsBrowserAuth.
const (
	SettingsBrowserAuthAPIOnly   SettingsBrowserAuth = "api_only"
	SettingsBrowserAuthAnonymous SettingsBrowserAuth = "anonymous"
	SettingsBrowserAuthSaml      SettingsBrowserAuth = "saml"
)

// Valid indicates whether the value is a known member of the SettingsBrowserAuth enum.
func (e SettingsBrowserAuth) Valid() bool {
	switch e {
	case SettingsBrowserAuthAPIOnly:
		return true
	case SettingsBrowserAuthAnonymous:
		return true
	case SettingsBrowserAuthSaml:
		return true
	default:
		return false
	}
}

// Defines values for Status.
const (
	Active Status = "active"
	Paused Status = "paused"
)

// Valid indicates whether the value is a known member of the Status enum.
func (e Status) Valid() bool {
	switch e {
	case Active:
		return true
	case Paused:
		return true
	default:
		return false
	}
}

// AuthSession defines model for AuthSession.
type AuthSession struct {
	Authenticated bool `json:"authenticated"`

	// CanManageAll Can manage all schedules and assign or clear their owners. True for configured SAML admins, valid Bearer keys and anonymous mode.
	CanManageAll bool                         `json:"can_manage_all"`
	ExpiresAt    nullable.Nullable[time.Time] `json:"expires_at"`
	Mode         AuthSessionMode              `json:"mode"`
	ReadAccess   bool                         `json:"read_access"`
	User         nullable.Nullable[struct {
		DisplayName string `json:"display_name"`

		// Email Normalized email from the SAML identity, or null when unavailable.
		Email   nullable.Nullable[string] `json:"email"`
		Subject string                    `json:"subject"`
	}] `json:"user"`

	// WriteAccess Can create schedules and modify those available to this caller. SAML users without an email cannot write.
	WriteAccess bool `json:"write_access"`
}

// AuthSessionMode defines model for AuthSession.Mode.
type AuthSessionMode string

// CodexProfile defines model for CodexProfile.
type CodexProfile struct {
	Effort      *CodexProfileEffort      `json:"effort,omitempty"`
	Personality *CodexProfilePersonality `json:"personality,omitempty"`
	ServiceTier *string                  `json:"service_tier,omitempty"`
	Summary     *CodexProfileSummary     `json:"summary,omitempty"`
}

// CodexProfileEffort defines model for CodexProfile.Effort.
type CodexProfileEffort string

// CodexProfilePersonality defines model for CodexProfile.Personality.
type CodexProfilePersonality string

// CodexProfileSummary defines model for CodexProfile.Summary.
type CodexProfileSummary string

// CreateSchedule defines model for CreateSchedule.
type CreateSchedule struct {
	Cron    string                    `json:"cron"`
	EnvFrom *EnvFrom                  `json:"env_from,omitempty"`
	Model   nullable.Nullable[string] `json:"model,omitempty"`
	Name    string                    `json:"name"`

	// OwnerEmail SAML non-admins must use their session email; omission fills it, explicit null is forbidden. Full-access callers may use any owner or null.
	OwnerEmail nullable.Nullable[string] `json:"owner_email,omitempty"`

	// Profile Exact Orpheus profile name; creation uses the configured default when omitted.
	Profile     *string      `json:"profile,omitempty"`
	Prompt      string       `json:"prompt"`
	SessionMode *SessionMode `json:"session_mode,omitempty"`
	Status      *Status      `json:"status,omitempty"`

	// Template Exact Orpheus template name; creation uses the configured default when omitted.
	Template *string `json:"template,omitempty"`
	Timezone string  `json:"timezone"`
}

// EnvFrom defines model for EnvFrom.
type EnvFrom = []string

// NullableOccurrence defines model for NullableOccurrence.
type NullableOccurrence struct {
	Attempts           int                                   `json:"attempts"`
	CreatedAt          time.Time                             `json:"created_at"`
	ErrorCode          nullable.Nullable[string]             `json:"error_code"`
	ExecutionStartedAt nullable.Nullable[time.Time]          `json:"execution_started_at"`
	FinishedAt         nullable.Nullable[time.Time]          `json:"finished_at"`
	ID                 openapi_types.UUID                    `json:"id"`
	NextAttemptAt      nullable.Nullable[time.Time]          `json:"next_attempt_at"`
	ObservedAt         nullable.Nullable[time.Time]          `json:"observed_at"`
	RunErrorCode       nullable.Nullable[string]             `json:"run_error_code"`
	RunID              nullable.Nullable[openapi_types.UUID] `json:"run_id"`
	RunStatus          nullable.Nullable[string]             `json:"run_status"`
	ScheduleID         openapi_types.UUID                    `json:"schedule_id"`
	ScheduledAt        time.Time                             `json:"scheduled_at"`
	SessionID          nullable.Nullable[openapi_types.UUID] `json:"session_id"`
	State              OccurrenceState                       `json:"state"`
	SyncErrorCode      nullable.Nullable[string]             `json:"sync_error_code"`
	UpdatedAt          time.Time                             `json:"updated_at"`
}

// Occurrence defines model for Occurrence.
type Occurrence struct {
	Attempts           int                                   `json:"attempts"`
	CreatedAt          time.Time                             `json:"created_at"`
	ErrorCode          nullable.Nullable[string]             `json:"error_code"`
	ExecutionStartedAt nullable.Nullable[time.Time]          `json:"execution_started_at"`
	FinishedAt         nullable.Nullable[time.Time]          `json:"finished_at"`
	ID                 openapi_types.UUID                    `json:"id"`
	NextAttemptAt      nullable.Nullable[time.Time]          `json:"next_attempt_at"`
	ObservedAt         nullable.Nullable[time.Time]          `json:"observed_at"`
	RunErrorCode       nullable.Nullable[string]             `json:"run_error_code"`
	RunID              nullable.Nullable[openapi_types.UUID] `json:"run_id"`
	RunStatus          nullable.Nullable[string]             `json:"run_status"`
	ScheduleID         openapi_types.UUID                    `json:"schedule_id"`
	ScheduledAt        time.Time                             `json:"scheduled_at"`
	SessionID          nullable.Nullable[openapi_types.UUID] `json:"session_id"`
	State              OccurrenceState                       `json:"state"`
	SyncErrorCode      nullable.Nullable[string]             `json:"sync_error_code"`
	UpdatedAt          time.Time                             `json:"updated_at"`
}

// OccurrencePage defines model for OccurrencePage.
type OccurrencePage struct {
	Items      []Occurrence              `json:"items"`
	NextCursor nullable.Nullable[string] `json:"next_cursor"`
}

// OccurrenceResult defines model for OccurrenceResult.
type OccurrenceResult struct {
	Error nullable.Nullable[struct {
		Code    string                    `json:"code"`
		Message string                    `json:"message"`
		Phase   nullable.Nullable[string] `json:"phase"`
	}] `json:"error"`
	FetchedAt    time.Time `json:"fetched_at"`
	FinalMessage nullable.Nullable[struct {
		CreatedAt time.Time          `json:"created_at"`
		ID        openapi_types.UUID `json:"id"`
		Text      string             `json:"text"`
	}] `json:"final_message"`
	RunStatus string `json:"run_status"`
}

// OccurrenceState defines model for OccurrenceState.
type OccurrenceState string

// Preview defines model for Preview.
type Preview struct {
	Times []time.Time `json:"times"`
}

// PreviewInput defines model for PreviewInput.
type PreviewInput struct {
	Cron     string `json:"cron"`
	Timezone string `json:"timezone"`
}

// Problem defines model for Problem.
type Problem struct {
	Error struct {
		Code    string `json:"code"`
		Details []struct {
			Code string   `json:"code"`
			Path []string `json:"path"`
		} `json:"details"`
		Message string                    `json:"message"`
		Phase   nullable.Nullable[string] `json:"phase"`
	} `json:"error"`
}

// Profile defines model for Profile.
type Profile struct {
	Codex        CodexProfile              `json:"codex"`
	Description  nullable.Nullable[string] `json:"description"`
	Harness      ProfileHarness            `json:"harness"`
	Instructions string                    `json:"instructions"`
	IsDefault    bool                      `json:"is_default"`
	Model        nullable.Nullable[string] `json:"model"`
	Name         string                    `json:"name"`
}

// ProfileHarness defines model for Profile.Harness.
type ProfileHarness string

// Profiles defines model for Profiles.
type Profiles struct {
	Items []Profile `json:"items"`
}

// Schedule defines model for Schedule.
type Schedule struct {
	// CanEdit Whether this caller may modify the current schedule. False for deleted schedules. Computed from current ownership even on an idempotent creation replay; busy state can still prevent session reset.
	CanEdit        bool                                  `json:"can_edit"`
	CreatedAt      time.Time                             `json:"created_at"`
	Cron           string                                `json:"cron"`
	DeletedAt      nullable.Nullable[time.Time]          `json:"deleted_at"`
	EnvFrom        EnvFrom                               `json:"env_from"`
	ID             openapi_types.UUID                    `json:"id"`
	LastOccurrence nullable.Nullable[NullableOccurrence] `json:"last_occurrence"`
	Model          nullable.Nullable[string]             `json:"model"`
	Name           string                                `json:"name"`
	NextRunAt      nullable.Nullable[time.Time]          `json:"next_run_at"`
	OwnerEmail     nullable.Nullable[string]             `json:"owner_email"`

	// Profile Stored Orpheus profile name.
	Profile     string      `json:"profile"`
	Prompt      string      `json:"prompt"`
	SessionMode SessionMode `json:"session_mode"`
	Status      Status      `json:"status"`

	// Template Stored Orpheus template name.
	Template  string    `json:"template"`
	Timezone  string    `json:"timezone"`
	UpdatedAt time.Time `json:"updated_at"`

	// URL Absolute Space Web card URL from ORPHEUS_PUBLIC_URL, or null when not configured. Computed at response time.
	URL nullable.Nullable[string] `json:"url"`
}

// SchedulePage defines model for SchedulePage.
type SchedulePage struct {
	Items      []Schedule                `json:"items"`
	NextCursor nullable.Nullable[string] `json:"next_cursor"`
}

// SessionMode defines model for SessionMode.
type SessionMode string

// Settings defines model for Settings.
type Settings struct {
	AllowedEnvFrom EnvFrom             `json:"allowed_env_from"`
	BaseEnvFrom    EnvFrom             `json:"base_env_from"`
	BrowserAuth    SettingsBrowserAuth `json:"browser_auth"`
}

// SettingsBrowserAuth defines model for Settings.BrowserAuth.
type SettingsBrowserAuth string

// Status defines model for Status.
type Status string

// Template defines model for Template.
type Template struct {
	Description nullable.Nullable[string] `json:"description"`
	IsDefault   bool                      `json:"is_default"`
	Name        string                    `json:"name"`
}

// Templates defines model for Templates.
type Templates struct {
	Items []Template `json:"items"`
}

// UpdateSchedule defines model for UpdateSchedule.
type UpdateSchedule struct {
	Cron       *string                   `json:"cron,omitempty"`
	EnvFrom    *EnvFrom                  `json:"env_from,omitempty"`
	Model      nullable.Nullable[string] `json:"model,omitempty"`
	Name       *string                   `json:"name,omitempty"`
	OwnerEmail nullable.Nullable[string] `json:"owner_email,omitempty"`

	// Profile Exact Orpheus profile name; omitted keeps the stored choice; a change starts a new reusable session.
	Profile     *string      `json:"profile,omitempty"`
	Prompt      *string      `json:"prompt,omitempty"`
	SessionMode *SessionMode `json:"session_mode,omitempty"`
	Status      *Status      `json:"status,omitempty"`

	// Template Exact Orpheus template name; omitted keeps the stored choice; a change starts a new reusable session.
	Template *string `json:"template,omitempty"`
	Timezone *string `json:"timezone,omitempty"`
}

// Cursor defines model for Cursor.
type Cursor = string

// ID defines model for ID.
type ID = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// OccurrenceID defines model for OccurrenceID.
type OccurrenceID = openapi_types.UUID

// OwnerEmail defines model for OwnerEmail.
type OwnerEmail = []string

// Unowned defines model for Unowned.
type Unowned = bool

// ListSchedulesParams defines parameters for ListSchedules.
type ListSchedulesParams struct {
	// OwnerEmail Repeated email filter; OR semantics, at most 100 distinct normalized emails.
	OwnerEmail *OwnerEmail `form:"owner_email,omitempty" json:"owner_email,omitempty"`

	// Unowned Only schedules without an owner. Cannot be combined with owner_email.
	Unowned *Unowned `form:"unowned,omitempty" json:"unowned,omitempty"`
	Status  *Status  `form:"status,omitempty" json:"status,omitempty"`
	Limit   *Limit   `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque position bound to normalized filters. New inserts are excluded from an ongoing traversal.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateScheduleParams defines parameters for CreateSchedule.
type CreateScheduleParams struct {
	// IdempotencyKey Retries with the same normalized body return the original response. Keys do not expire.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListOccurrencesParams defines parameters for ListOccurrences.
type ListOccurrencesParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque position bound to normalized filters. New inserts are excluded from an ongoing traversal.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// BrowserLoginParams defines parameters for BrowserLogin.
type BrowserLoginParams struct {
	Next *string `form:"next,omitempty" json:"next,omitempty"`
}

// CreateScheduleJSONRequestBody defines body for CreateSchedule for application/json ContentType.
type CreateScheduleJSONRequestBody = CreateSchedule

// PreviewScheduleJSONRequestBody defines body for PreviewSchedule for application/json ContentType.
type PreviewScheduleJSONRequestBody = PreviewInput

// UpdateScheduleJSONRequestBody defines body for UpdateSchedule for application/json ContentType.
type UpdateScheduleJSONRequestBody = UpdateSchedule

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetAuthSession Get browser access state
	// (GET /api/v1/auth/session)
	GetAuthSession(w http.ResponseWriter, r *http.Request)
	// ListSchedules List schedules
	// (GET /api/v1/schedules)
	ListSchedules(w http.ResponseWriter, r *http.Request, params ListSchedulesParams)
	// CreateSchedule Create a schedule
	// (POST /api/v1/schedules)
	CreateSchedule(w http.ResponseWriter, r *http.Request, params CreateScheduleParams)
	// PreviewSchedule Preview five future cron occurrences
	// (POST /api/v1/schedules/preview)
	PreviewSchedule(w http.ResponseWriter, r *http.Request)
	// GetProfiles Get Orpheus profiles and the creation default
	// (GET /api/v1/schedules/profiles)
	GetProfiles(w http.ResponseWriter, r *http.Request)
	// GetSettings Get allowed environment names
	// (GET /api/v1/schedules/settings)
	GetSettings(w http.ResponseWriter, r *http.Request)
	// GetTemplates Get Orpheus templates and the creation default
	// (GET /api/v1/schedules/templates)
	GetTemplates(w http.ResponseWriter, r *http.Request)
	// DeleteSchedule Soft delete a schedule
	// (DELETE /api/v1/schedules/{id})
	DeleteSchedule(w http.ResponseWriter, r *http.Request, id ID)
	// GetSchedule Get a schedule including deleted records
	// (GET /api/v1/schedules/{id})
	GetSchedule(w http.ResponseWriter, r *http.Request, id ID)
	// UpdateSchedule Update selected schedule fields
	// (PATCH /api/v1/schedules/{id})
	UpdateSchedule(w http.ResponseWriter, r *http.Request, id ID)
	// ListOccurrences Read stored history without calling the core
	// (GET /api/v1/schedules/{id}/occurrences)
	ListOccurrences(w http.ResponseWriter, r *http.Request, id ID, params ListOccurrencesParams)
	// GetOccurrence Read a stored occurrence without calling the core
	// (GET /api/v1/schedules/{id}/occurrences/{occurrence_id})
	GetOccurrence(w http.ResponseWriter, r *http.Request, id ID, occurrenceID OccurrenceID)
	// GetOccurrenceResult Explicitly fetch the current result from the Orpheus core
	// (GET /api/v1/schedules/{id}/occurrences/{occurrence_id}/result)
	GetOccurrenceResult(w http.ResponseWriter, r *http.Request, id ID, occurrenceID OccurrenceID)
	// ResetSession Detach the reusable session for the next occurrence
	// (POST /api/v1/schedules/{id}/reset-session)
	ResetSession(w http.ResponseWriter, r *http.Request, id ID)
	// BrowserCallback Consume a signed SAML HTTP-POST response
	// (POST /auth/callback)
	BrowserCallback(w http.ResponseWriter, r *http.Request)
	// BrowserLogin Start SP-initiated SAML login
	// (GET /auth/login)
	BrowserLogin(w http.ResponseWriter, r *http.Request, params BrowserLoginParams)
	// BrowserLogout Revoke the local browser session
	// (POST /auth/logout)
	BrowserLogout(w http.ResponseWriter, r *http.Request)
	// SamlMetadata Read service provider metadata
	// (GET /saml/metadata)
	SamlMetadata(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAuthSession operation middleware
func (siw *ServerInterfaceWrapper) GetAuthSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSchedules operation middleware
func (siw *ServerInterfaceWrapper) ListSchedules(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSchedulesParams

	// ------------- Optional query parameter "owner_email" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "owner_email", r.URL.Query(), &params.OwnerEmail, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "owner_email"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner_email", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "unowned" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "unowned", r.URL.Query(), &params.Unowned, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "unowned"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "unowned", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSchedules(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSchedule operation middleware
func (siw *ServerInterfaceWrapper) CreateSchedule(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateScheduleParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSchedule(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewSchedule operation middleware
func (siw *ServerInterfaceWrapper) PreviewSchedule(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewSchedule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProfiles operation middleware
func (siw *ServerInterfaceWrapper) GetProfiles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProfiles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTemplates operation middleware
func (siw *ServerInterfaceWrapper) GetTemplates(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTemplates(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSchedule operation middleware
func (siw *ServerInterfaceWrapper) DeleteSchedule(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSchedule operation middleware
func (siw *ServerInterfaceWrapper) GetSchedule(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSchedule operation middleware
func (siw *ServerInterfaceWrapper) UpdateSchedule(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOccurrences operation middleware
func (siw *ServerInterfaceWrapper) ListOccurrences(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOccurrencesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOccurrences(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOccurrence operation middleware
func (siw *ServerInterfaceWrapper) GetOccurrence(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "occurrence_id" -------------
	var occurrenceID OccurrenceID

	err = runtime.BindStyledParameterWithOptions("simple", "occurrence_id", r.PathValue("occurrence_id"), &occurrenceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "occurrence_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOccurrence(w, r, id, occurrenceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOccurrenceResult operation middleware
func (siw *ServerInterfaceWrapper) GetOccurrenceResult(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "occurrence_id" -------------
	var occurrenceID OccurrenceID

	err = runtime.BindStyledParameterWithOptions("simple", "occurrence_id", r.PathValue("occurrence_id"), &occurrenceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "occurrence_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOccurrenceResult(w, r, id, occurrenceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetSession operation middleware
func (siw *ServerInterfaceWrapper) ResetSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetSession(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BrowserCallback operation middleware
func (siw *ServerInterfaceWrapper) BrowserCallback(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BrowserCallback(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BrowserLogin operation middleware
func (siw *ServerInterfaceWrapper) BrowserLogin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params BrowserLoginParams

	// ------------- Optional query parameter "next" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "next", r.URL.Query(), &params.Next, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "next"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "next", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BrowserLogin(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BrowserLogout operation middleware
func (siw *ServerInterfaceWrapper) BrowserLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BrowserLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SamlMetadata operation middleware
func (siw *ServerInterfaceWrapper) SamlMetadata(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SamlMetadata(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules", wrapper.ListSchedules)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/schedules", wrapper.CreateSchedule)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/schedules/{id}", wrapper.DeleteSchedule)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules/{id}", wrapper.GetSchedule)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/schedules/{id}", wrapper.UpdateSchedule)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules/profiles", wrapper.GetProfiles)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules/templates", wrapper.GetTemplates)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules/settings", wrapper.GetSettings)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/schedules/preview", wrapper.PreviewSchedule)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/auth/session", wrapper.GetAuthSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules/{id}/occurrences", wrapper.ListOccurrences)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules/{id}/occurrences/{occurrence_id}", wrapper.GetOccurrence)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schedules/{id}/occurrences/{occurrence_id}/result", wrapper.GetOccurrenceResult)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/schedules/{id}/reset-session", wrapper.ResetSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/login", wrapper.BrowserLogin)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/callback", wrapper.BrowserCallback)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.BrowserLogout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/saml/metadata", wrapper.SamlMetadata)

	return m
}

type ProblemJSONResponse Problem

type GetAuthSessionRequestObject struct {
}

type GetAuthSessionResponseObject interface {
	VisitGetAuthSessionResponse(w http.ResponseWriter) error
}

type GetAuthSession200JSONResponse AuthSession

func (response GetAuthSession200JSONResponse) VisitGetAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthSessiondefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetAuthSessiondefaultJSONResponse) VisitGetAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulesRequestObject struct {
	Params ListSchedulesParams
}

type ListSchedulesResponseObject interface {
	VisitListSchedulesResponse(w http.ResponseWriter) error
}

type ListSchedules200JSONResponse SchedulePage

func (response ListSchedules200JSONResponse) VisitListSchedulesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulesdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListSchedulesdefaultJSONResponse) VisitListSchedulesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateScheduleRequestObject struct {
	Params CreateScheduleParams
	Body   *CreateScheduleJSONRequestBody
}

type CreateScheduleResponseObject interface {
	VisitCreateScheduleResponse(w http.ResponseWriter) error
}

type CreateSchedule201JSONResponse Schedule

func (response CreateSchedule201JSONResponse) VisitCreateScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateScheduledefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateScheduledefaultJSONResponse) VisitCreateScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewScheduleRequestObject struct {
	Body *PreviewScheduleJSONRequestBody
}

type PreviewScheduleResponseObject interface {
	VisitPreviewScheduleResponse(w http.ResponseWriter) error
}

type PreviewSchedule200JSONResponse Preview

func (response PreviewSchedule200JSONResponse) VisitPreviewScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewScheduledefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PreviewScheduledefaultJSONResponse) VisitPreviewScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfilesRequestObject struct {
}

type GetProfilesResponseObject interface {
	VisitGetProfilesResponse(w http.ResponseWriter) error
}

type GetProfiles200JSONResponse Profiles

func (response GetProfiles200JSONResponse) VisitGetProfilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfilesdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetProfilesdefaultJSONResponse) VisitGetProfilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSettingsRequestObject struct {
}

type GetSettingsResponseObject interface {
	VisitGetSettingsResponse(w http.ResponseWriter) error
}

type GetSettings200JSONResponse Settings

func (response GetSettings200JSONResponse) VisitGetSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSettingsdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetSettingsdefaultJSONResponse) VisitGetSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetTemplatesRequestObject struct {
}

type GetTemplatesResponseObject interface {
	VisitGetTemplatesResponse(w http.ResponseWriter) error
}

type GetTemplates200JSONResponse Templates

func (response GetTemplates200JSONResponse) VisitGetTemplatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTemplatesdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetTemplatesdefaultJSONResponse) VisitGetTemplatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteScheduleRequestObject struct {
	ID ID `json:"id"`
}

type DeleteScheduleResponseObject interface {
	VisitDeleteScheduleResponse(w http.ResponseWriter) error
}

type DeleteSchedule204Response struct {
}

func (response DeleteSchedule204Response) VisitDeleteScheduleResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteScheduledefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteScheduledefaultJSONResponse) VisitDeleteScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetScheduleRequestObject struct {
	ID ID `json:"id"`
}

type GetScheduleResponseObject interface {
	VisitGetScheduleResponse(w http.ResponseWriter) error
}

type GetSchedule200JSONResponse Schedule

func (response GetSchedule200JSONResponse) VisitGetScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetScheduledefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetScheduledefaultJSONResponse) VisitGetScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateScheduleRequestObject struct {
	ID   ID `json:"id"`
	Body *UpdateScheduleJSONRequestBody
}

type UpdateScheduleResponseObject interface {
	VisitUpdateScheduleResponse(w http.ResponseWriter) error
}

type UpdateSchedule200JSONResponse Schedule

func (response UpdateSchedule200JSONResponse) VisitUpdateScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateScheduledefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response UpdateScheduledefaultJSONResponse) VisitUpdateScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListOccurrencesRequestObject struct {
	ID     ID `json:"id"`
	Params ListOccurrencesParams
}

type ListOccurrencesResponseObject interface {
	VisitListOccurrencesResponse(w http.ResponseWriter) error
}

type ListOccurrences200JSONResponse OccurrencePage

func (response ListOccurrences200JSONResponse) VisitListOccurrencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOccurrencesdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListOccurrencesdefaultJSONResponse) VisitListOccurrencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetOccurrenceRequestObject struct {
	ID           ID           `json:"id"`
	OccurrenceID OccurrenceID `json:"occurrence_id"`
}

type GetOccurrenceResponseObject interface {
	VisitGetOccurrenceResponse(w http.ResponseWriter) error
}

type GetOccurrence200JSONResponse Occurrence

func (response GetOccurrence200JSONResponse) VisitGetOccurrenceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOccurrencedefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetOccurrencedefaultJSONResponse) VisitGetOccurrenceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetOccurrenceResultRequestObject struct {
	ID           ID           `json:"id"`
	OccurrenceID OccurrenceID `json:"occurrence_id"`
}

type GetOccurrenceResultResponseObject interface {
	VisitGetOccurrenceResultResponse(w http.ResponseWriter) error
}

type GetOccurrenceResult200JSONResponse OccurrenceResult

func (response GetOccurrenceResult200JSONResponse) VisitGetOccurrenceResultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOccurrenceResultdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetOccurrenceResultdefaultJSONResponse) VisitGetOccurrenceResultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ResetSessionRequestObject struct {
	ID ID `json:"id"`
}

type ResetSessionResponseObject interface {
	VisitResetSessionResponse(w http.ResponseWriter) error
}

type ResetSession200JSONResponse Schedule

func (response ResetSession200JSONResponse) VisitResetSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ResetSessiondefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ResetSessiondefaultJSONResponse) VisitResetSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type BrowserCallbackRequestObject struct {
}

type BrowserCallbackResponseObject interface {
	VisitBrowserCallbackResponse(w http.ResponseWriter) error
}

type BrowserCallback303ResponseHeaders struct {
	Location *string
}

type BrowserCallback303Response struct {
	Headers BrowserCallback303ResponseHeaders
}

func (response BrowserCallback303Response) VisitBrowserCallbackResponse(w http.ResponseWriter) error {
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(303)
	return nil
}

type BrowserCallbackdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response BrowserCallbackdefaultJSONResponse) VisitBrowserCallbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type BrowserLoginRequestObject struct {
	Params BrowserLoginParams
}

type BrowserLoginResponseObject interface {
	VisitBrowserLoginResponse(w http.ResponseWriter) error
}

type BrowserLogin302ResponseHeaders struct {
	Location *string
}

type BrowserLogin302Response struct {
	Headers BrowserLogin302ResponseHeaders
}

func (response BrowserLogin302Response) VisitBrowserLoginResponse(w http.ResponseWriter) error {
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(302)
	return nil
}

type BrowserLogindefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response BrowserLogindefaultJSONResponse) VisitBrowserLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type BrowserLogoutRequestObject struct {
}

type BrowserLogoutResponseObject interface {
	VisitBrowserLogoutResponse(w http.ResponseWriter) error
}

type BrowserLogout204Response struct {
}

func (response BrowserLogout204Response) VisitBrowserLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type BrowserLogoutdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response BrowserLogoutdefaultJSONResponse) VisitBrowserLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SamlMetadataRequestObject struct {
}

type SamlMetadataResponseObject interface {
	VisitSamlMetadataResponse(w http.ResponseWriter) error
}

type SamlMetadata200ApplicationSamlmetadataXMLResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response SamlMetadata200ApplicationSamlmetadataXMLResponse) VisitSamlMetadataResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/samlmetadata+xml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type SamlMetadatadefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response SamlMetadatadefaultJSONResponse) VisitSamlMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetAuthSession Get browser access state
	// (GET /api/v1/auth/session)
	GetAuthSession(ctx context.Context, request GetAuthSessionRequestObject) (GetAuthSessionResponseObject, error)
	// ListSchedules List schedules
	// (GET /api/v1/schedules)
	ListSchedules(ctx context.Context, request ListSchedulesRequestObject) (ListSchedulesResponseObject, error)
	// CreateSchedule Create a schedule
	// (POST /api/v1/schedules)
	CreateSchedule(ctx context.Context, request CreateScheduleRequestObject) (CreateScheduleResponseObject, error)
	// PreviewSchedule Preview five future cron occurrences
	// (POST /api/v1/schedules/preview)
	PreviewSchedule(ctx context.Context, request PreviewScheduleRequestObject) (PreviewScheduleResponseObject, error)
	// GetProfiles Get Orpheus profiles and the creation default
	// (GET /api/v1/schedules/profiles)
	GetProfiles(ctx context.Context, request GetProfilesRequestObject) (GetProfilesResponseObject, error)
	// GetSettings Get allowed environment names
	// (GET /api/v1/schedules/settings)
	GetSettings(ctx context.Context, request GetSettingsRequestObject) (GetSettingsResponseObject, error)
	// GetTemplates Get Orpheus templates and the creation default
	// (GET /api/v1/schedules/templates)
	GetTemplates(ctx context.Context, request GetTemplatesRequestObject) (GetTemplatesResponseObject, error)
	// DeleteSchedule Soft delete a schedule
	// (DELETE /api/v1/schedules/{id})
	DeleteSchedule(ctx context.Context, request DeleteScheduleRequestObject) (DeleteScheduleResponseObject, error)
	// GetSchedule Get a schedule including deleted records
	// (GET /api/v1/schedules/{id})
	GetSchedule(ctx context.Context, request GetScheduleRequestObject) (GetScheduleResponseObject, error)
	// UpdateSchedule Update selected schedule fields
	// (PATCH /api/v1/schedules/{id})
	UpdateSchedule(ctx context.Context, request UpdateScheduleRequestObject) (UpdateScheduleResponseObject, error)
	// ListOccurrences Read stored history without calling the core
	// (GET /api/v1/schedules/{id}/occurrences)
	ListOccurrences(ctx context.Context, request ListOccurrencesRequestObject) (ListOccurrencesResponseObject, error)
	// GetOccurrence Read a stored occurrence without calling the core
	// (GET /api/v1/schedules/{id}/occurrences/{occurrence_id})
	GetOccurrence(ctx context.Context, request GetOccurrenceRequestObject) (GetOccurrenceResponseObject, error)
	// GetOccurrenceResult Explicitly fetch the current result from the Orpheus core
	// (GET /api/v1/schedules/{id}/occurrences/{occurrence_id}/result)
	GetOccurrenceResult(ctx context.Context, request GetOccurrenceResultRequestObject) (GetOccurrenceResultResponseObject, error)
	// ResetSession Detach the reusable session for the next occurrence
	// (POST /api/v1/schedules/{id}/reset-session)
	ResetSession(ctx context.Context, request ResetSessionRequestObject) (ResetSessionResponseObject, error)
	// BrowserCallback Consume a signed SAML HTTP-POST response
	// (POST /auth/callback)
	BrowserCallback(ctx context.Context, request BrowserCallbackRequestObject) (BrowserCallbackResponseObject, error)
	// BrowserLogin Start SP-initiated SAML login
	// (GET /auth/login)
	BrowserLogin(ctx context.Context, request BrowserLoginRequestObject) (BrowserLoginResponseObject, error)
	// BrowserLogout Revoke the local browser session
	// (POST /auth/logout)
	BrowserLogout(ctx context.Context, request BrowserLogoutRequestObject) (BrowserLogoutResponseObject, error)
	// SamlMetadata Read service provider metadata
	// (GET /saml/metadata)
	SamlMetadata(ctx context.Context, request SamlMetadataRequestObject) (SamlMetadataResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAuthSession operation middleware
func (sh *strictHandler) GetAuthSession(w http.ResponseWriter, r *http.Request) {
	var request GetAuthSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthSession(ctx, request.(GetAuthSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthSessionResponseObject); ok {
		if err := validResponse.VisitGetAuthSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSchedules operation middleware
func (sh *strictHandler) ListSchedules(w http.ResponseWriter, r *http.Request, params ListSchedulesParams) {
	var request ListSchedulesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSchedules(ctx, request.(ListSchedulesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSchedules")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSchedulesResponseObject); ok {
		if err := validResponse.VisitListSchedulesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSchedule operation middleware
func (sh *strictHandler) CreateSchedule(w http.ResponseWriter, r *http.Request, params CreateScheduleParams) {
	var request CreateScheduleRequestObject

	request.Params = params

	var body CreateScheduleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSchedule(ctx, request.(CreateScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateScheduleResponseObject); ok {
		if err := validResponse.VisitCreateScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PreviewSchedule operation middleware
func (sh *strictHandler) PreviewSchedule(w http.ResponseWriter, r *http.Request) {
	var request PreviewScheduleRequestObject

	var body PreviewScheduleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PreviewSchedule(ctx, request.(PreviewScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PreviewSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PreviewScheduleResponseObject); ok {
		if err := validResponse.VisitPreviewScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProfiles operation middleware
func (sh *strictHandler) GetProfiles(w http.ResponseWriter, r *http.Request) {
	var request GetProfilesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProfiles(ctx, request.(GetProfilesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProfiles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProfilesResponseObject); ok {
		if err := validResponse.VisitGetProfilesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSettings operation middleware
func (sh *strictHandler) GetSettings(w http.ResponseWriter, r *http.Request) {
	var request GetSettingsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSettings(ctx, request.(GetSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSettings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSettingsResponseObject); ok {
		if err := validResponse.VisitGetSettingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTemplates operation middleware
func (sh *strictHandler) GetTemplates(w http.ResponseWriter, r *http.Request) {
	var request GetTemplatesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTemplates(ctx, request.(GetTemplatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTemplates")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTemplatesResponseObject); ok {
		if err := validResponse.VisitGetTemplatesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSchedule operation middleware
func (sh *strictHandler) DeleteSchedule(w http.ResponseWriter, r *http.Request, id ID) {
	var request DeleteScheduleRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSchedule(ctx, request.(DeleteScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteScheduleResponseObject); ok {
		if err := validResponse.VisitDeleteScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSchedule operation middleware
func (sh *strictHandler) GetSchedule(w http.ResponseWriter, r *http.Request, id ID) {
	var request GetScheduleRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSchedule(ctx, request.(GetScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetScheduleResponseObject); ok {
		if err := validResponse.VisitGetScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSchedule operation middleware
func (sh *strictHandler) UpdateSchedule(w http.ResponseWriter, r *http.Request, id ID) {
	var request UpdateScheduleRequestObject

	request.ID = id

	var body UpdateScheduleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSchedule(ctx, request.(UpdateScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSchedule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateScheduleResponseObject); ok {
		if err := validResponse.VisitUpdateScheduleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOccurrences operation middleware
func (sh *strictHandler) ListOccurrences(w http.ResponseWriter, r *http.Request, id ID, params ListOccurrencesParams) {
	var request ListOccurrencesRequestObject

	request.ID = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOccurrences(ctx, request.(ListOccurrencesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOccurrences")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOccurrencesResponseObject); ok {
		if err := validResponse.VisitListOccurrencesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOccurrence operation middleware
func (sh *strictHandler) GetOccurrence(w http.ResponseWriter, r *http.Request, id ID, occurrenceID OccurrenceID) {
	var request GetOccurrenceRequestObject

	request.ID = id
	request.OccurrenceID = occurrenceID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOccurrence(ctx, request.(GetOccurrenceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOccurrence")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOccurrenceResponseObject); ok {
		if err := validResponse.VisitGetOccurrenceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOccurrenceResult operation middleware
func (sh *strictHandler) GetOccurrenceResult(w http.ResponseWriter, r *http.Request, id ID, occurrenceID OccurrenceID) {
	var request GetOccurrenceResultRequestObject

	request.ID = id
	request.OccurrenceID = occurrenceID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOccurrenceResult(ctx, request.(GetOccurrenceResultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOccurrenceResult")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOccurrenceResultResponseObject); ok {
		if err := validResponse.VisitGetOccurrenceResultResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResetSession operation middleware
func (sh *strictHandler) ResetSession(w http.ResponseWriter, r *http.Request, id ID) {
	var request ResetSessionRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResetSession(ctx, request.(ResetSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResetSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResetSessionResponseObject); ok {
		if err := validResponse.VisitResetSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BrowserCallback operation middleware
func (sh *strictHandler) BrowserCallback(w http.ResponseWriter, r *http.Request) {
	var request BrowserCallbackRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BrowserCallback(ctx, request.(BrowserCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BrowserCallback")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BrowserCallbackResponseObject); ok {
		if err := validResponse.VisitBrowserCallbackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BrowserLogin operation middleware
func (sh *strictHandler) BrowserLogin(w http.ResponseWriter, r *http.Request, params BrowserLoginParams) {
	var request BrowserLoginRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BrowserLogin(ctx, request.(BrowserLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BrowserLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BrowserLoginResponseObject); ok {
		if err := validResponse.VisitBrowserLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BrowserLogout operation middleware
func (sh *strictHandler) BrowserLogout(w http.ResponseWriter, r *http.Request) {
	var request BrowserLogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BrowserLogout(ctx, request.(BrowserLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BrowserLogout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BrowserLogoutResponseObject); ok {
		if err := validResponse.VisitBrowserLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SamlMetadata operation middleware
func (sh *strictHandler) SamlMetadata(w http.ResponseWriter, r *http.Request) {
	var request SamlMetadataRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SamlMetadata(ctx, request.(SamlMetadataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SamlMetadata")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SamlMetadataResponseObject); ok {
		if err := validResponse.VisitSamlMetadataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Dxpc9u4kn8FxX0fkl1akh1P1Yz9KdfsuJ4Tu6xk39amvCyIbEmYgAADgLY1Kf/3rcbBS9RlW36z8/LJ",
	"pggCfXeju4HvUSrzQgoQRkcn36OCKpqDAWWf3pZKS4X/ZaBTxQrDpIhOoouCfiuBFFIz/IVMZCkyYiQR",
	"UuWUsz8gI1PGcZoB+Qi3hAkNymhCFRC4S3mZ4Qglc0IFkWImmZgRo+gNKE35IIojhut8K0EtojgSNIfo",
	"JEodOHGk0znkFOHK6d05iJmZRyc/H/5yFEc5E+GHwzgyiwI/1EYxMYvu7+Po7B1+ZmcvqJnXk7MsiiMF",
	"30qmIItOjCqhudAUMTPRSVSWdmTPzBnkhTQg0sXfYbFMtCswioEmt8zMiZkD0TSHJsUmMlsQBaZUwr6X",
	"is2YoJwo0IUUGgbk77DQJEM6GwJ3BVNQ0WoONANV49MA5wDh2Q2Zc5YzU1GqwwduXzYnzGBKS26ik59G",
	"MfKE5WUenRyNRpYh7qlmBxMGZqDsQhdpWioFIoWVnJHVkOTRTLq4FaDe55TxPgYVQA1kBPC9F+BTcnFF",
	"NORUGJbqmFBDcqkNORyNSMa0YSI1TSbabzVyBe4KLjMIUPYRUiI0if2kRU5mILcK2EGgwogqRRf4rM2C",
	"4w+IOT6PDTWlXsU47d42l/qbgml0Ev3bsLYDQ/dWD/1kSLfPAmHNekyB4AuCH2Ql98ItS2PVGpEbkLdU",
	"oLROgKQynzABmdOABu6r9L30izbh9QSYSMmBiugegQv6YfG+VHLCIcd/UykMCCvGtCg4SykCPfxdI+Tf",
	"tyRCmM+u1MZ9bFSZmlJBRl5fnhFQSqoBOR4dklRBBsIwynVMjkevyNvx1a9EqopSyVSqCcsyEPj+mORM",
	"ayZm+PALSaWYcpaamBwfHZEbyllmIY/JT6NXpBT0hjJOJxwGljceUkTkdWnmY9CaOQxpllkDTfmlkgUo",
	"w5BGU8o1xFHR+Ol7REszR4hT1IA+QsdRSkWSU0FnkFDeoz9vqSDuPaGcN4SCioxQrdlMIAlSDlShgWPK",
	"CYEekE+qBDLFl1JM2cySdPz6wzmhWc6Ejh0RyBugChT5Cgs/qZBikctSk1xm1hQuQ+3MpE6oaVmIjBo4",
	"MCwHFLeSW3IGVV3Sutzq8fcIBBqyLxEtWCIFR1GtQIjiSNOcR9c93yugWULTFLTuJ22pQW1kWBfMNgMz",
	"pgtOF4nTnR7TAf1W72PHdjm3jP7HMoBZOTaLGFmHEJDbOYi2EG5BQV1OfofU9AB23zToX6qBcRuhAH5N",
	"XenG3cfRrWIGGuRdlspUATXQkchcZmy6IGYuNZAKG4xizJxpklLO0X5ZKiB/WsbNkSp1ts0C0Cd9Hdys",
	"GMUdVWtLRwebJaXzotIS6z6avJUZ3F0qOWUcdrQEMJ1KZZriLqSAyHtyijBweYvPkLEyj+Jozmboru/8",
	"35zeIZzcKNqrDQUojZAws+hZZaoYiMzqVqHoLKeGpb3TaFA3LIXEMKc7ayM/lMA8p6q1Ii2NRBJLkTKN",
	"a2dgKOOWKRaa674QYpnWVrrGXrh2pHaqpNgCehA3CSrmJm/1Xtz8isO80eLLU29U1WBAGqF1COTWQdiM",
	"ZZaU0CqRkOLA2XOSl9qgUnk3oJ3Lclp1SqT1hlJgCMY1YSbGYJezlBlngpgmlf8ckF9Lzg+cwnit1SSn",
	"Czs/FQvnZIL5GkTxrgQpajVqY/X+jqaGXKhiDqUmfhhB+p06k4M4lBq0NacN1+bDZWdKZc6MgWwZsD5A",
	"8sJsI+uOnknwW2uDPDf2Aw7FT6sAcpvIMI4M5AWnZiN1wrg9kge9+R+otpsI1DHL3sF46sZOJRvT9dnX",
	"oGfNYL2gxoBC1P/3y+uD/6EHfyTX/p/RwS/J9b//LYo3RPRxVAr2rYQzNycK5H0cffQSWu+VHhkrIKB5",
	"4Xb81f5stLw/Q1rYLdG66GkJIxsHJ6mXvY3qBXeQlohIog1VGxbbONuUCabnj5yEZVvsJuNIwJ1JPC0f",
	"tZ6coDN7JNCqFMmOpMdP+nHd6tPaVmwcXu17tiRtGL+b5AW790CcEJ+N9rJWwrEdjt8tRLor6csi21Gx",
	"OlaLZVFNpqT1ZGcN6LR0uLVui16VMLRY2xbNFbraVrolQVymT8tExLU1WtaoPtO7gxX8YfV+WL0fVu+H",
	"1ftLWb1LOtvV8lUhavXPdrzuyzhbYNOqMLSB5V322fXbk6zH9gq0LSzshK8l9CNj5CDTy8lA0JrO+t8V",
	"c6phd7J4kQgzh3n6KDMFk853NBBTrCIlDbgfQ5YHuMYtrZ+Buy0ShO5bHNrS8T5ata31+mlb6t8gstfa",
	"qEvF9VI7DjY1pJoKEBku69Ka1KRz90TTFAqXBtRfWVHY/6YhCZVSkQLH//sSYJcKbhjc7qgbyKS2LdiO",
	"iTm987vSn+xOvH5oW4gOXd1yfdTy4J+JojT7SZo9NCGwTQKgUWZ6csO0pSFy2co2L59iXlt93aEK2aGe",
	"L97a6fso13Uoz2dPa5Itw9WZwTFqBeMfkFRHiO42Od5W0r5bbdwiuppTJXwNJNgdt26f9WBC2/Ilk6Kf",
	"yUwnVVm/r2ZV5Ze3zihvlYZrIl2jFJaLPUYd+FvQruGa3mvg1GDdWg1xk/WB+dAiAhUJZK5hoyU00T/m",
	"YOagmiUtmxuvil9AnM8yVXVsQH7FNWw5NgMOBrLqnR6QtzIvShPad8LHrpA7ZwWBG8CWHiySsdCCYup8",
	"rwIs6p2SSakXxMbqWEUj2jDOSaHwa1PVAxRoMP1l3YfEIVu6DY/0o7alD6jXbBklcapNIls5kHUL9OSO",
	"n782ZMN9jLAelS5oF5ieqogzNlJB1lvF+cuVZDq4tmoyT1lgechGP45K1VM5fD3RkpcGyLigKZB/wISk",
	"VGXk89W5s0AXV5e/vf88Ti4/vzk/e5t8vjrvtCpghb4uLjUMGDVVZx0xzFGgVj/FNgtl39YEsYhrixxv",
	"LC/FdVtW8HFBWBu87EhQ3Okdq+zNusRHUw1bZm7ZqqxzTntPQISF/mnph6YCNjsU4DbCCUsNvSHVGIxh",
	"YrZrkEE5l7eQJQ/wGROq4UHfKXmrQSXYivLwxqYOddvAxMt4ddbtpXxl6yqQUsNurALRUq/YCX9qWLwd",
	"CL9rfL0pIn5EnLshfA0I7jd+rcj48AD2s7U3P3ph9hKqrOs38W0S5CtA4RoqtHP26VyyFE4JJemcihn+",
	"Tm0rPhFwS9CYITAh5P7X6kJ5PqLtkopazkxoSEvFzAL1ymfvJkAVqNfefluKWGtkf66jq7kxRcPgN3qD",
	"bcN1KuVXBnXHdZL8JrU5kI5cicaYK/FY1pPSguGJAtsRzcRU9gSa3gD4fuAchLE9l568c4b/LLA53FAu",
	"Z/adspl+AiIrJBNGEwW0jlWxmjJXUshS88Wpa7nUoTcaLFuCQuBkFaM1cHBJAuQSZykIn1FyGH84++SD",
	"NkcsfTIcygKElqVKYSDVbOg/GubM5a+YQeWMAmQuMH19eRbF0Q0oR99oNDgcjHA4TkYLFp1ErwajwavI",
	"5dcsD4e0YMObwyF6w6GuWTMDq15oGu2m+SyLTqL/BNPs7u50vR+NRk/W8d5cpq/rvXS9qfZF5Q37Jqwg",
	"bDTR18IcnXy5brRlIoLEiynx3XyhlmcoBlVfbHt7dI2TBNJViYmVdDtn2oyrUXHrhNOXfrjrIcPGeZH7",
	"eOPocEpii6GV7do40h3F2WKgP611f71H2WjtAfYhHJU4IN/qvFNDCGpmXqM3ktps7jdN6yZwDG9tbqs6",
	"gRDaTmnVbOhbRrHNlHEecl3WP3iLT963GlKlwrMINtPmPnXHuLQ9+7F85mPgTzLEjRMM9jyDg3ZOb4BM",
	"cV6nB2i52kLdaTneVao7R9WcxHwrQZs3Mls8mbB0oLxvh5G+ubEjqodPLqr7FVOHI6EVl1dIap/NGhZ1",
	"BS/IcZvPvkbWYPQ++NSqxG3FpdFTr71fJvlFyJRZxTKlAoKbDVJnPPRufKurCaucdVVx2Cvx/Bp7pR46",
	"5s6mw5krWz0Iif2wyA5k1I18ySoyVjmVfTq1sMbeyehTIgTEDVNS2LgYA9GdpM80kwGr6FZnDPZIuHqR",
	"ZxPACvknkcDvLLt30QMHA9vFEW6siyPqGKJRIXsHgkEWtij+QPeKQGDJs7+zs7cMfot5xz1APhmhx3Jq",
	"An4bPVq8WmdXQj/6f+bdrc5WhCBM4NUFeFdBKIwqSKXK1oSnu8Vl72wsZvuDthNGl99fKYxWSfwpRZ/J",
	"aJ7ADWe0HyWxnZTffkKUziLPHKQ8j7A5HH3GolF0J1MGPNO72rVhM7hZtzu+aAVBu0nsn2pz2umR3Suz",
	"roB201nV+WDss0Aj4Y61KXhK67AVu4ffW3dm3K8LFGqiRc/CmmdgCw2MqanwHLzZrASty04eyMuhqjqi",
	"N7PUd08/C2P9Wntlb8i6YAoHTDpvNTD5BHKVqwkh45+XzQo0mING5vdh4cLWKTC73r4i1yuc/BnS08/j",
	"jN+BoV6+uuWekD0k2EbQsDHrHDRm+NH0TGj6tZnu6eFZLjMX0A0IhlCYhWwS6+7g9vb2APtUDkrFQaQy",
	"C1fqANa6+IJI4S7vuPI42ijwCjhd2L70xiVG5AN7MyAXwjXlEB+52fEhFS8kmk+qgIR4a0A+Cy2tHtoI",
	"2BPSj/ndBi/L4vHGzfc2EKEjIa9Gr3ru7pBCl7ndi7CZCHfC/Pbp0+XB5cX4U7V2FPvrr+xU59KRanm+",
	"//LlooxwmVIeJBwLMoO+W4aqotx9W6D2fbHQmXD33XA5Y8J3Sb44Ho1exoT5V5YSAX98efgyJo2bReyG",
	"mFm5zfD18cuYSFuespezSZWTF8eHr17aZqn2d0P0nnQGzUteyIufRq9eDtYWcLbmVq0SFsGGK1unDqfE",
	"JthvmQZ7ZRJOkAhpEhAWy4HTR3u1xAShcDymoYEMuUxe4E4IvyRKlgb0y9PqtoG+atyAfJQES6JIpULJ",
	"uwVxgkaMKrVZKeXnFq8l79J3yZVwR1l6r7Q7Gh3/vFwhvl5SnaMe2hmqDBlfHjDBDLMyb8nJPWRb6Yv9",
	"4iy7xG67P6WCNBQ4KMgGHQgmrr5Vi7jjNuTF8dHRU6rDeg60dECWZrVTuHJmd+mWjAt7PaC11f994GOd",
	"A3vPmBdR+FZSTowkhwNSVXzMqdv+h+mw/j8g7yRo2yhpQOVMoL3B18j6Ro/DKlFH8LdJVF3BjfzqZna6",
	"GXyMDtXmf4oQuXsWkfFN6r04Hnnr+ED+b8YWRUDTnA9zMDSjhq4M6sc05x/CoJ1iK5w/TP8fdzlvU25J",
	"jeMlluE21920hAbwhiFtKnifl2GvN7i3GrDdebUezc637fabL9e4J+h22Nhf0VbjtMEB1H0mJ8OhlYq5",
	"1Obk59HhyIbyPn5cssNzqpqnMGISSicuwYelLF9LHNSepQ5C7+PujG/ajRbh+jz/pcXr/vr+/wYA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
