// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: browser_auth.sql

package db

import (
	"context"
	"time"
)

const cleanupBrowserLogins = `-- name: CleanupBrowserLogins :execrows
DELETE FROM browser_login_requests WHERE id IN (
    SELECT id FROM browser_login_requests WHERE expires_at <= clock_timestamp()
    ORDER BY expires_at LIMIT 1000 FOR UPDATE SKIP LOCKED
)
`

func (q *Queries) CleanupBrowserLogins(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupBrowserLogins)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanupBrowserSessions = `-- name: CleanupBrowserSessions :execrows
DELETE FROM browser_sessions WHERE token_hash IN (
    SELECT token_hash FROM browser_sessions WHERE expires_at <= clock_timestamp()
    ORDER BY expires_at LIMIT 1000 FOR UPDATE SKIP LOCKED
)
`

func (q *Queries) CleanupBrowserSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupBrowserSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeBrowserLogin = `-- name: ConsumeBrowserLogin :one
DELETE FROM browser_login_requests
WHERE id = $1 AND browser_nonce_hash = $2 AND expires_at > clock_timestamp()
RETURNING id, request_id, browser_nonce_hash, return_path, expires_at, previous_session_hash
`

type ConsumeBrowserLoginParams struct {
	ID               string `json:"id"`
	BrowserNonceHash []byte `json:"browser_nonce_hash"`
}

func (q *Queries) ConsumeBrowserLogin(ctx context.Context, arg ConsumeBrowserLoginParams) (BrowserLoginRequest, error) {
	row := q.db.QueryRow(ctx, consumeBrowserLogin, arg.ID, arg.BrowserNonceHash)
	var i BrowserLoginRequest
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.BrowserNonceHash,
		&i.ReturnPath,
		&i.ExpiresAt,
		&i.PreviousSessionHash,
	)
	return i, err
}

const deleteBrowserSession = `-- name: DeleteBrowserSession :exec
DELETE FROM browser_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteBrowserSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteBrowserSession, tokenHash)
	return err
}

const getBrowserLogin = `-- name: GetBrowserLogin :one
SELECT id, request_id, browser_nonce_hash, return_path, expires_at, previous_session_hash FROM browser_login_requests
WHERE id = $1 AND browser_nonce_hash = $2 AND expires_at > clock_timestamp()
`

type GetBrowserLoginParams struct {
	ID               string `json:"id"`
	BrowserNonceHash []byte `json:"browser_nonce_hash"`
}

func (q *Queries) GetBrowserLogin(ctx context.Context, arg GetBrowserLoginParams) (BrowserLoginRequest, error) {
	row := q.db.QueryRow(ctx, getBrowserLogin, arg.ID, arg.BrowserNonceHash)
	var i BrowserLoginRequest
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.BrowserNonceHash,
		&i.ReturnPath,
		&i.ExpiresAt,
		&i.PreviousSessionHash,
	)
	return i, err
}

const getBrowserSession = `-- name: GetBrowserSession :one
SELECT token_hash, subject, display_name, created_at, expires_at FROM browser_sessions WHERE token_hash = $1 AND expires_at > clock_timestamp()
`

func (q *Queries) GetBrowserSession(ctx context.Context, tokenHash []byte) (BrowserSession, error) {
	row := q.db.QueryRow(ctx, getBrowserSession, tokenHash)
	var i BrowserSession
	err := row.Scan(
		&i.TokenHash,
		&i.Subject,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertBrowserLogin = `-- name: InsertBrowserLogin :exec
INSERT INTO browser_login_requests (id, request_id, browser_nonce_hash, return_path, expires_at, previous_session_hash)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertBrowserLoginParams struct {
	ID                  string    `json:"id"`
	RequestID           string    `json:"request_id"`
	BrowserNonceHash    []byte    `json:"browser_nonce_hash"`
	ReturnPath          string    `json:"return_path"`
	ExpiresAt           time.Time `json:"expires_at"`
	PreviousSessionHash []byte    `json:"previous_session_hash"`
}

func (q *Queries) InsertBrowserLogin(ctx context.Context, arg InsertBrowserLoginParams) error {
	_, err := q.db.Exec(ctx, insertBrowserLogin,
		arg.ID,
		arg.RequestID,
		arg.BrowserNonceHash,
		arg.ReturnPath,
		arg.ExpiresAt,
		arg.PreviousSessionHash,
	)
	return err
}

const insertBrowserSession = `-- name: InsertBrowserSession :exec
INSERT INTO browser_sessions (token_hash, subject, display_name, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertBrowserSessionParams struct {
	TokenHash   []byte    `json:"token_hash"`
	Subject     string    `json:"subject"`
	DisplayName string    `json:"display_name"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) InsertBrowserSession(ctx context.Context, arg InsertBrowserSessionParams) error {
	_, err := q.db.Exec(ctx, insertBrowserSession,
		arg.TokenHash,
		arg.Subject,
		arg.DisplayName,
		arg.ExpiresAt,
	)
	return err
}
