// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Schedule struct {
	ID            uuid.UUID  `json:"id"`
	Sequence      *int64     `json:"sequence"`
	Name          string     `json:"name"`
	Prompt        string     `json:"prompt"`
	Cron          string     `json:"cron"`
	Timezone      string     `json:"timezone"`
	Status        string     `json:"status"`
	Model         *string    `json:"model"`
	SessionMode   string     `json:"session_mode"`
	OwnerEmail    *string    `json:"owner_email"`
	EnvFrom       []string   `json:"env_from"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	NextRunAt     *time.Time `json:"next_run_at"`
	CronStartedAt time.Time  `json:"cron_started_at"`
	DeletedAt     *time.Time `json:"deleted_at"`
}

type ScheduleCreateKey struct {
	Key         uuid.UUID       `json:"key"`
	Fingerprint string          `json:"fingerprint"`
	Response    json.RawMessage `json:"response"`
}
