// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: occurrences.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptOccurrence = `-- name: AcceptOccurrence :exec
UPDATE schedule_occurrences SET state='accepted',session_id=$2,run_id=$3,run_status='accepted',observed_at=$4,updated_at=$4,error_code=NULL,next_attempt_at=$4 WHERE id=$1
`

type AcceptOccurrenceParams struct {
	ID         uuid.UUID  `json:"id"`
	SessionID  *uuid.UUID `json:"session_id"`
	RunID      *uuid.UUID `json:"run_id"`
	ObservedAt *time.Time `json:"observed_at"`
}

func (q *Queries) AcceptOccurrence(ctx context.Context, arg AcceptOccurrenceParams) error {
	_, err := q.db.Exec(ctx, acceptOccurrence,
		arg.ID,
		arg.SessionID,
		arg.RunID,
		arg.ObservedAt,
	)
	return err
}

const activeOccurrence = `-- name: ActiveOccurrence :one
SELECT id, sequence, schedule_id, scheduled_at, state, created_at, updated_at, completed_at, request_path, request_body, request_key, fingerprint, reusable, uncertain, attempts, next_attempt_at, error_code, session_id, run_id, run_status, observed_at, execution_started_at, finished_at, run_error_code, sync_error_code FROM schedule_occurrences WHERE schedule_id=$1 AND completed_at IS NULL
`

func (q *Queries) ActiveOccurrence(ctx context.Context, scheduleID uuid.UUID) (ScheduleOccurrence, error) {
	row := q.db.QueryRow(ctx, activeOccurrence, scheduleID)
	var i ScheduleOccurrence
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.ScheduleID,
		&i.ScheduledAt,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RequestPath,
		&i.RequestBody,
		&i.RequestKey,
		&i.Fingerprint,
		&i.Reusable,
		&i.Uncertain,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.ErrorCode,
		&i.SessionID,
		&i.RunID,
		&i.RunStatus,
		&i.ObservedAt,
		&i.ExecutionStartedAt,
		&i.FinishedAt,
		&i.RunErrorCode,
		&i.SyncErrorCode,
	)
	return i, err
}

const advanceSchedule = `-- name: AdvanceSchedule :exec
UPDATE schedules SET next_run_at=$2 WHERE id=$1
`

type AdvanceScheduleParams struct {
	ID        uuid.UUID  `json:"id"`
	NextRunAt *time.Time `json:"next_run_at"`
}

func (q *Queries) AdvanceSchedule(ctx context.Context, arg AdvanceScheduleParams) error {
	_, err := q.db.Exec(ctx, advanceSchedule, arg.ID, arg.NextRunAt)
	return err
}

const cancelPending = `-- name: CancelPending :exec
UPDATE schedule_occurrences SET state='cancelled',error_code='schedule_inactive',completed_at=$2,updated_at=$2,next_attempt_at=NULL WHERE schedule_id=$1 AND state='pending'
`

type CancelPendingParams struct {
	ScheduleID  uuid.UUID  `json:"schedule_id"`
	CompletedAt *time.Time `json:"completed_at"`
}

func (q *Queries) CancelPending(ctx context.Context, arg CancelPendingParams) error {
	_, err := q.db.Exec(ctx, cancelPending, arg.ScheduleID, arg.CompletedAt)
	return err
}

const clearReusableSession = `-- name: ClearReusableSession :exec
UPDATE schedules SET reusable_session_id=NULL,reusable_fingerprint=NULL WHERE id=$1
`

func (q *Queries) ClearReusableSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearReusableSession, id)
	return err
}

const dueSchedules = `-- name: DueSchedules :many
SELECT id FROM schedules WHERE status='active' AND deleted_at IS NULL AND next_run_at <= $1
AND NOT EXISTS (SELECT 1 FROM schedule_occurrences o WHERE o.schedule_id=schedules.id AND o.completed_at IS NULL AND (o.state != 'accepted' OR o.sync_error_code IS NOT NULL))
ORDER BY next_run_at,id LIMIT 100
`

func (q *Queries) DueSchedules(ctx context.Context, nextRunAt *time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dueSchedules, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishDispatch = `-- name: FinishDispatch :exec
UPDATE schedule_occurrences SET state=$2,error_code=$3,completed_at=$4,updated_at=$4,next_attempt_at=NULL WHERE id=$1
`

type FinishDispatchParams struct {
	ID          uuid.UUID  `json:"id"`
	State       string     `json:"state"`
	ErrorCode   *string    `json:"error_code"`
	CompletedAt *time.Time `json:"completed_at"`
}

func (q *Queries) FinishDispatch(ctx context.Context, arg FinishDispatchParams) error {
	_, err := q.db.Exec(ctx, finishDispatch,
		arg.ID,
		arg.State,
		arg.ErrorCode,
		arg.CompletedAt,
	)
	return err
}

const getOccurrence = `-- name: GetOccurrence :one
SELECT id, sequence, schedule_id, scheduled_at, state, created_at, updated_at, completed_at, request_path, request_body, request_key, fingerprint, reusable, uncertain, attempts, next_attempt_at, error_code, session_id, run_id, run_status, observed_at, execution_started_at, finished_at, run_error_code, sync_error_code FROM schedule_occurrences WHERE schedule_id=$1 AND id=$2
`

type GetOccurrenceParams struct {
	ScheduleID uuid.UUID `json:"schedule_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetOccurrence(ctx context.Context, arg GetOccurrenceParams) (ScheduleOccurrence, error) {
	row := q.db.QueryRow(ctx, getOccurrence, arg.ScheduleID, arg.ID)
	var i ScheduleOccurrence
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.ScheduleID,
		&i.ScheduledAt,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RequestPath,
		&i.RequestBody,
		&i.RequestKey,
		&i.Fingerprint,
		&i.Reusable,
		&i.Uncertain,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.ErrorCode,
		&i.SessionID,
		&i.RunID,
		&i.RunStatus,
		&i.ObservedAt,
		&i.ExecutionStartedAt,
		&i.FinishedAt,
		&i.RunErrorCode,
		&i.SyncErrorCode,
	)
	return i, err
}

const insertOccurrence = `-- name: InsertOccurrence :one
INSERT INTO schedule_occurrences(id,schedule_id,scheduled_at,state,created_at,updated_at,completed_at,request_key,error_code)
VALUES ($1,$2,$3,$4,$5,$5,$6,$7,$8) RETURNING id, sequence, schedule_id, scheduled_at, state, created_at, updated_at, completed_at, request_path, request_body, request_key, fingerprint, reusable, uncertain, attempts, next_attempt_at, error_code, session_id, run_id, run_status, observed_at, execution_started_at, finished_at, run_error_code, sync_error_code
`

type InsertOccurrenceParams struct {
	ID          uuid.UUID  `json:"id"`
	ScheduleID  uuid.UUID  `json:"schedule_id"`
	ScheduledAt time.Time  `json:"scheduled_at"`
	State       string     `json:"state"`
	CreatedAt   time.Time  `json:"created_at"`
	CompletedAt *time.Time `json:"completed_at"`
	RequestKey  uuid.UUID  `json:"request_key"`
	ErrorCode   *string    `json:"error_code"`
}

func (q *Queries) InsertOccurrence(ctx context.Context, arg InsertOccurrenceParams) (ScheduleOccurrence, error) {
	row := q.db.QueryRow(ctx, insertOccurrence,
		arg.ID,
		arg.ScheduleID,
		arg.ScheduledAt,
		arg.State,
		arg.CreatedAt,
		arg.CompletedAt,
		arg.RequestKey,
		arg.ErrorCode,
	)
	var i ScheduleOccurrence
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.ScheduleID,
		&i.ScheduledAt,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RequestPath,
		&i.RequestBody,
		&i.RequestKey,
		&i.Fingerprint,
		&i.Reusable,
		&i.Uncertain,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.ErrorCode,
		&i.SessionID,
		&i.RunID,
		&i.RunStatus,
		&i.ObservedAt,
		&i.ExecutionStartedAt,
		&i.FinishedAt,
		&i.RunErrorCode,
		&i.SyncErrorCode,
	)
	return i, err
}

const lastOccurrence = `-- name: LastOccurrence :one
SELECT id, sequence, schedule_id, scheduled_at, state, created_at, updated_at, completed_at, request_path, request_body, request_key, fingerprint, reusable, uncertain, attempts, next_attempt_at, error_code, session_id, run_id, run_status, observed_at, execution_started_at, finished_at, run_error_code, sync_error_code FROM schedule_occurrences WHERE schedule_id=$1 ORDER BY scheduled_at DESC,id DESC LIMIT 1
`

func (q *Queries) LastOccurrence(ctx context.Context, scheduleID uuid.UUID) (ScheduleOccurrence, error) {
	row := q.db.QueryRow(ctx, lastOccurrence, scheduleID)
	var i ScheduleOccurrence
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.ScheduleID,
		&i.ScheduledAt,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RequestPath,
		&i.RequestBody,
		&i.RequestKey,
		&i.Fingerprint,
		&i.Reusable,
		&i.Uncertain,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.ErrorCode,
		&i.SessionID,
		&i.RunID,
		&i.RunStatus,
		&i.ObservedAt,
		&i.ExecutionStartedAt,
		&i.FinishedAt,
		&i.RunErrorCode,
		&i.SyncErrorCode,
	)
	return i, err
}

const lastOccurrences = `-- name: LastOccurrences :many
SELECT DISTINCT ON (schedule_id) id, sequence, schedule_id, scheduled_at, state, created_at, updated_at, completed_at, request_path, request_body, request_key, fingerprint, reusable, uncertain, attempts, next_attempt_at, error_code, session_id, run_id, run_status, observed_at, execution_started_at, finished_at, run_error_code, sync_error_code FROM schedule_occurrences
WHERE schedule_id = ANY($1::uuid[]) ORDER BY schedule_id,scheduled_at DESC,id DESC
`

func (q *Queries) LastOccurrences(ctx context.Context, dollar_1 []uuid.UUID) ([]ScheduleOccurrence, error) {
	rows, err := q.db.Query(ctx, lastOccurrences, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleOccurrence{}
	for rows.Next() {
		var i ScheduleOccurrence
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.ScheduleID,
			&i.ScheduledAt,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.RequestPath,
			&i.RequestBody,
			&i.RequestKey,
			&i.Fingerprint,
			&i.Reusable,
			&i.Uncertain,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.ErrorCode,
			&i.SessionID,
			&i.RunID,
			&i.RunStatus,
			&i.ObservedAt,
			&i.ExecutionStartedAt,
			&i.FinishedAt,
			&i.RunErrorCode,
			&i.SyncErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestCompletion = `-- name: LatestCompletion :one
SELECT COALESCE(finished_at,completed_at)::timestamptz AS boundary FROM schedule_occurrences
WHERE schedule_id=$1 AND state IN ('accepted','failed') AND completed_at IS NOT NULL
ORDER BY COALESCE(finished_at,completed_at) DESC LIMIT 1
`

func (q *Queries) LatestCompletion(ctx context.Context, scheduleID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, latestCompletion, scheduleID)
	var boundary time.Time
	err := row.Scan(&boundary)
	return boundary, err
}

const listOccurrences = `-- name: ListOccurrences :many
SELECT id, sequence, schedule_id, scheduled_at, state, created_at, updated_at, completed_at, request_path, request_body, request_key, fingerprint, reusable, uncertain, attempts, next_attempt_at, error_code, session_id, run_id, run_status, observed_at, execution_started_at, finished_at, run_error_code, sync_error_code FROM schedule_occurrences WHERE schedule_id = $1 AND sequence <= $2::bigint
AND (NOT $3::boolean OR (scheduled_at,id) < ($4::timestamptz,$5::uuid))
ORDER BY scheduled_at DESC,id DESC LIMIT $6::int
`

type ListOccurrencesParams struct {
	ScheduleID    uuid.UUID `json:"schedule_id"`
	UpperSequence int64     `json:"upper_sequence"`
	HasPosition   bool      `json:"has_position"`
	PositionTime  time.Time `json:"position_time"`
	PositionID    uuid.UUID `json:"position_id"`
	PageLimit     int       `json:"page_limit"`
}

func (q *Queries) ListOccurrences(ctx context.Context, arg ListOccurrencesParams) ([]ScheduleOccurrence, error) {
	rows, err := q.db.Query(ctx, listOccurrences,
		arg.ScheduleID,
		arg.UpperSequence,
		arg.HasPosition,
		arg.PositionTime,
		arg.PositionID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleOccurrence{}
	for rows.Next() {
		var i ScheduleOccurrence
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.ScheduleID,
			&i.ScheduledAt,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.RequestPath,
			&i.RequestBody,
			&i.RequestKey,
			&i.Fingerprint,
			&i.Reusable,
			&i.Uncertain,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.ErrorCode,
			&i.SessionID,
			&i.RunID,
			&i.RunStatus,
			&i.ObservedAt,
			&i.ExecutionStartedAt,
			&i.FinishedAt,
			&i.RunErrorCode,
			&i.SyncErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttempt = `-- name: MarkAttempt :one
UPDATE schedule_occurrences SET attempts=attempts+1,uncertain=true,updated_at=$2 WHERE id=$1 AND state='dispatching' RETURNING id, sequence, schedule_id, scheduled_at, state, created_at, updated_at, completed_at, request_path, request_body, request_key, fingerprint, reusable, uncertain, attempts, next_attempt_at, error_code, session_id, run_id, run_status, observed_at, execution_started_at, finished_at, run_error_code, sync_error_code
`

type MarkAttemptParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) MarkAttempt(ctx context.Context, arg MarkAttemptParams) (ScheduleOccurrence, error) {
	row := q.db.QueryRow(ctx, markAttempt, arg.ID, arg.UpdatedAt)
	var i ScheduleOccurrence
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.ScheduleID,
		&i.ScheduledAt,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RequestPath,
		&i.RequestBody,
		&i.RequestKey,
		&i.Fingerprint,
		&i.Reusable,
		&i.Uncertain,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.ErrorCode,
		&i.SessionID,
		&i.RunID,
		&i.RunStatus,
		&i.ObservedAt,
		&i.ExecutionStartedAt,
		&i.FinishedAt,
		&i.RunErrorCode,
		&i.SyncErrorCode,
	)
	return i, err
}

const observeFailure = `-- name: ObserveFailure :exec
UPDATE schedule_occurrences SET sync_error_code=$2,next_attempt_at=$3,updated_at=$4 WHERE id=$1
`

type ObserveFailureParams struct {
	ID            uuid.UUID  `json:"id"`
	SyncErrorCode *string    `json:"sync_error_code"`
	NextAttemptAt *time.Time `json:"next_attempt_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

func (q *Queries) ObserveFailure(ctx context.Context, arg ObserveFailureParams) error {
	_, err := q.db.Exec(ctx, observeFailure,
		arg.ID,
		arg.SyncErrorCode,
		arg.NextAttemptAt,
		arg.UpdatedAt,
	)
	return err
}

const observeRun = `-- name: ObserveRun :exec
UPDATE schedule_occurrences SET run_status=$2,observed_at=$3,updated_at=$3,execution_started_at=$4,finished_at=$5,run_error_code=$6,sync_error_code=NULL,completed_at=$7,next_attempt_at=$8 WHERE id=$1
`

type ObserveRunParams struct {
	ID                 uuid.UUID  `json:"id"`
	RunStatus          *string    `json:"run_status"`
	ObservedAt         *time.Time `json:"observed_at"`
	ExecutionStartedAt *time.Time `json:"execution_started_at"`
	FinishedAt         *time.Time `json:"finished_at"`
	RunErrorCode       *string    `json:"run_error_code"`
	CompletedAt        *time.Time `json:"completed_at"`
	NextAttemptAt      *time.Time `json:"next_attempt_at"`
}

func (q *Queries) ObserveRun(ctx context.Context, arg ObserveRunParams) error {
	_, err := q.db.Exec(ctx, observeRun,
		arg.ID,
		arg.RunStatus,
		arg.ObservedAt,
		arg.ExecutionStartedAt,
		arg.FinishedAt,
		arg.RunErrorCode,
		arg.CompletedAt,
		arg.NextAttemptAt,
	)
	return err
}

const occurrenceUpperBound = `-- name: OccurrenceUpperBound :one
SELECT COALESCE(max(sequence),0)::bigint FROM schedule_occurrences WHERE schedule_id=$1
`

func (q *Queries) OccurrenceUpperBound(ctx context.Context, scheduleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, occurrenceUpperBound, scheduleID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const prepareOccurrence = `-- name: PrepareOccurrence :one
UPDATE schedule_occurrences SET state='dispatching',request_path=$2,request_body=$3,request_key=$4,fingerprint=$5,reusable=$6,updated_at=$7
WHERE id=$1 AND state='pending' RETURNING id, sequence, schedule_id, scheduled_at, state, created_at, updated_at, completed_at, request_path, request_body, request_key, fingerprint, reusable, uncertain, attempts, next_attempt_at, error_code, session_id, run_id, run_status, observed_at, execution_started_at, finished_at, run_error_code, sync_error_code
`

type PrepareOccurrenceParams struct {
	ID          uuid.UUID `json:"id"`
	RequestPath *string   `json:"request_path"`
	RequestBody []byte    `json:"request_body"`
	RequestKey  uuid.UUID `json:"request_key"`
	Fingerprint *string   `json:"fingerprint"`
	Reusable    bool      `json:"reusable"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) PrepareOccurrence(ctx context.Context, arg PrepareOccurrenceParams) (ScheduleOccurrence, error) {
	row := q.db.QueryRow(ctx, prepareOccurrence,
		arg.ID,
		arg.RequestPath,
		arg.RequestBody,
		arg.RequestKey,
		arg.Fingerprint,
		arg.Reusable,
		arg.UpdatedAt,
	)
	var i ScheduleOccurrence
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.ScheduleID,
		&i.ScheduledAt,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RequestPath,
		&i.RequestBody,
		&i.RequestKey,
		&i.Fingerprint,
		&i.Reusable,
		&i.Uncertain,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.ErrorCode,
		&i.SessionID,
		&i.RunID,
		&i.RunStatus,
		&i.ObservedAt,
		&i.ExecutionStartedAt,
		&i.FinishedAt,
		&i.RunErrorCode,
		&i.SyncErrorCode,
	)
	return i, err
}

const retryOccurrence = `-- name: RetryOccurrence :exec
UPDATE schedule_occurrences SET error_code=$2,uncertain=$3,next_attempt_at=$4,updated_at=$5 WHERE id=$1
`

type RetryOccurrenceParams struct {
	ID            uuid.UUID  `json:"id"`
	ErrorCode     *string    `json:"error_code"`
	Uncertain     bool       `json:"uncertain"`
	NextAttemptAt *time.Time `json:"next_attempt_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

func (q *Queries) RetryOccurrence(ctx context.Context, arg RetryOccurrenceParams) error {
	_, err := q.db.Exec(ctx, retryOccurrence,
		arg.ID,
		arg.ErrorCode,
		arg.Uncertain,
		arg.NextAttemptAt,
		arg.UpdatedAt,
	)
	return err
}

const saveReusableSession = `-- name: SaveReusableSession :exec
UPDATE schedules SET reusable_session_id=$2,reusable_fingerprint=$3 WHERE id=$1
`

type SaveReusableSessionParams struct {
	ID                  uuid.UUID  `json:"id"`
	ReusableSessionID   *uuid.UUID `json:"reusable_session_id"`
	ReusableFingerprint *string    `json:"reusable_fingerprint"`
}

func (q *Queries) SaveReusableSession(ctx context.Context, arg SaveReusableSessionParams) error {
	_, err := q.db.Exec(ctx, saveReusableSession, arg.ID, arg.ReusableSessionID, arg.ReusableFingerprint)
	return err
}

const workOccurrences = `-- name: WorkOccurrences :many
SELECT id, sequence, schedule_id, scheduled_at, state, created_at, updated_at, completed_at, request_path, request_body, request_key, fingerprint, reusable, uncertain, attempts, next_attempt_at, error_code, session_id, run_id, run_status, observed_at, execution_started_at, finished_at, run_error_code, sync_error_code FROM schedule_occurrences WHERE completed_at IS NULL AND (next_attempt_at IS NULL OR next_attempt_at <= $1 OR (state='accepted' AND sync_error_code IS NULL AND EXISTS (SELECT 1 FROM schedules s WHERE s.id=schedule_id AND s.next_run_at <= $1)))
ORDER BY next_attempt_at NULLS FIRST,scheduled_at,id LIMIT 100
`

func (q *Queries) WorkOccurrences(ctx context.Context, nextAttemptAt *time.Time) ([]ScheduleOccurrence, error) {
	rows, err := q.db.Query(ctx, workOccurrences, nextAttemptAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleOccurrence{}
	for rows.Next() {
		var i ScheduleOccurrence
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.ScheduleID,
			&i.ScheduledAt,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.RequestPath,
			&i.RequestBody,
			&i.RequestKey,
			&i.Fingerprint,
			&i.Reusable,
			&i.Uncertain,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.ErrorCode,
			&i.SessionID,
			&i.RunID,
			&i.RunStatus,
			&i.ObservedAt,
			&i.ExecutionStartedAt,
			&i.FinishedAt,
			&i.RunErrorCode,
			&i.SyncErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
