// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (id,name,prompt,cron,timezone,status,model,session_mode,owner_email,services,created_at,updated_at,next_run_at,cron_started_at,profile,template)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11,$12,$11,$13,$14) RETURNING id, sequence, name, prompt, cron, timezone, status, model, session_mode, owner_email, created_at, updated_at, next_run_at, cron_started_at, deleted_at, reusable_session_id, reusable_fingerprint, profile, template, services
`

type CreateScheduleParams struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	Prompt      string     `json:"prompt"`
	Cron        string     `json:"cron"`
	Timezone    string     `json:"timezone"`
	Status      string     `json:"status"`
	Model       *string    `json:"model"`
	SessionMode string     `json:"session_mode"`
	OwnerEmail  *string    `json:"owner_email"`
	Services    []string   `json:"services"`
	CreatedAt   time.Time  `json:"created_at"`
	NextRunAt   *time.Time `json:"next_run_at"`
	Profile     string     `json:"profile"`
	Template    string     `json:"template"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.ID,
		arg.Name,
		arg.Prompt,
		arg.Cron,
		arg.Timezone,
		arg.Status,
		arg.Model,
		arg.SessionMode,
		arg.OwnerEmail,
		arg.Services,
		arg.CreatedAt,
		arg.NextRunAt,
		arg.Profile,
		arg.Template,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.Name,
		&i.Prompt,
		&i.Cron,
		&i.Timezone,
		&i.Status,
		&i.Model,
		&i.SessionMode,
		&i.OwnerEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextRunAt,
		&i.CronStartedAt,
		&i.DeletedAt,
		&i.ReusableSessionID,
		&i.ReusableFingerprint,
		&i.Profile,
		&i.Template,
		&i.Services,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
UPDATE schedules SET deleted_at=$2,updated_at=$2,next_run_at=NULL WHERE id=$1 AND deleted_at IS NULL
`

type DeleteScheduleParams struct {
	ID        uuid.UUID  `json:"id"`
	DeletedAt *time.Time `json:"deleted_at"`
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error {
	_, err := q.db.Exec(ctx, deleteSchedule, arg.ID, arg.DeletedAt)
	return err
}

const getCreateKey = `-- name: GetCreateKey :one
SELECT fingerprint,response FROM schedule_create_keys WHERE key=$1
`

type GetCreateKeyRow struct {
	Fingerprint string          `json:"fingerprint"`
	Response    json.RawMessage `json:"response"`
}

func (q *Queries) GetCreateKey(ctx context.Context, key uuid.UUID) (GetCreateKeyRow, error) {
	row := q.db.QueryRow(ctx, getCreateKey, key)
	var i GetCreateKeyRow
	err := row.Scan(&i.Fingerprint, &i.Response)
	return i, err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, sequence, name, prompt, cron, timezone, status, model, session_mode, owner_email, created_at, updated_at, next_run_at, cron_started_at, deleted_at, reusable_session_id, reusable_fingerprint, profile, template, services FROM schedules WHERE id=$1
`

func (q *Queries) GetSchedule(ctx context.Context, id uuid.UUID) (Schedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.Name,
		&i.Prompt,
		&i.Cron,
		&i.Timezone,
		&i.Status,
		&i.Model,
		&i.SessionMode,
		&i.OwnerEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextRunAt,
		&i.CronStartedAt,
		&i.DeletedAt,
		&i.ReusableSessionID,
		&i.ReusableFingerprint,
		&i.Profile,
		&i.Template,
		&i.Services,
	)
	return i, err
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, sequence, name, prompt, cron, timezone, status, model, session_mode, owner_email, created_at, updated_at, next_run_at, cron_started_at, deleted_at, reusable_session_id, reusable_fingerprint, profile, template, services FROM schedules
WHERE deleted_at IS NULL
 AND sequence <= $1::bigint
 AND ($2::text = '' OR status = $2::text)
 AND (NOT $3::boolean OR owner_email IS NULL)
 AND (cardinality($4::text[]) = 0 OR owner_email = ANY($4::text[]))
 AND (NOT $5::boolean OR (created_at,id) < ($6::timestamptz,$7::uuid))
ORDER BY created_at DESC,id DESC LIMIT $8::int
`

type ListSchedulesParams struct {
	UpperSequence int64     `json:"upper_sequence"`
	Status        string    `json:"status"`
	Unowned       bool      `json:"unowned"`
	Owners        []string  `json:"owners"`
	HasPosition   bool      `json:"has_position"`
	PositionTime  time.Time `json:"position_time"`
	PositionID    uuid.UUID `json:"position_id"`
	PageLimit     int       `json:"page_limit"`
}

func (q *Queries) ListSchedules(ctx context.Context, arg ListSchedulesParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedules,
		arg.UpperSequence,
		arg.Status,
		arg.Unowned,
		arg.Owners,
		arg.HasPosition,
		arg.PositionTime,
		arg.PositionID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.Name,
			&i.Prompt,
			&i.Cron,
			&i.Timezone,
			&i.Status,
			&i.Model,
			&i.SessionMode,
			&i.OwnerEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextRunAt,
			&i.CronStartedAt,
			&i.DeletedAt,
			&i.ReusableSessionID,
			&i.ReusableFingerprint,
			&i.Profile,
			&i.Template,
			&i.Services,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSchedule = `-- name: LockSchedule :one
SELECT id, sequence, name, prompt, cron, timezone, status, model, session_mode, owner_email, created_at, updated_at, next_run_at, cron_started_at, deleted_at, reusable_session_id, reusable_fingerprint, profile, template, services FROM schedules WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockSchedule(ctx context.Context, id uuid.UUID) (Schedule, error) {
	row := q.db.QueryRow(ctx, lockSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.Name,
		&i.Prompt,
		&i.Cron,
		&i.Timezone,
		&i.Status,
		&i.Model,
		&i.SessionMode,
		&i.OwnerEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextRunAt,
		&i.CronStartedAt,
		&i.DeletedAt,
		&i.ReusableSessionID,
		&i.ReusableFingerprint,
		&i.Profile,
		&i.Template,
		&i.Services,
	)
	return i, err
}

const reserveCreateKey = `-- name: ReserveCreateKey :one
INSERT INTO schedule_create_keys (key,fingerprint) VALUES ($1,$2) ON CONFLICT DO NOTHING RETURNING key
`

type ReserveCreateKeyParams struct {
	Key         uuid.UUID `json:"key"`
	Fingerprint string    `json:"fingerprint"`
}

func (q *Queries) ReserveCreateKey(ctx context.Context, arg ReserveCreateKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, reserveCreateKey, arg.Key, arg.Fingerprint)
	var key uuid.UUID
	err := row.Scan(&key)
	return key, err
}

const saveCreateResponse = `-- name: SaveCreateResponse :exec
UPDATE schedule_create_keys SET response=$2 WHERE key=$1
`

type SaveCreateResponseParams struct {
	Key      uuid.UUID       `json:"key"`
	Response json.RawMessage `json:"response"`
}

func (q *Queries) SaveCreateResponse(ctx context.Context, arg SaveCreateResponseParams) error {
	_, err := q.db.Exec(ctx, saveCreateResponse, arg.Key, arg.Response)
	return err
}

const scheduleUpperBound = `-- name: ScheduleUpperBound :one
SELECT COALESCE(max(sequence),0)::bigint FROM schedules
`

func (q *Queries) ScheduleUpperBound(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, scheduleUpperBound)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE schedules SET name=$2,prompt=$3,cron=$4,timezone=$5,status=$6,model=$7,session_mode=$8,owner_email=$9,services=$10,updated_at=$11,next_run_at=$12,cron_started_at=$13,profile=$14,template=$15
WHERE id=$1 RETURNING id, sequence, name, prompt, cron, timezone, status, model, session_mode, owner_email, created_at, updated_at, next_run_at, cron_started_at, deleted_at, reusable_session_id, reusable_fingerprint, profile, template, services
`

type UpdateScheduleParams struct {
	ID            uuid.UUID  `json:"id"`
	Name          string     `json:"name"`
	Prompt        string     `json:"prompt"`
	Cron          string     `json:"cron"`
	Timezone      string     `json:"timezone"`
	Status        string     `json:"status"`
	Model         *string    `json:"model"`
	SessionMode   string     `json:"session_mode"`
	OwnerEmail    *string    `json:"owner_email"`
	Services      []string   `json:"services"`
	UpdatedAt     time.Time  `json:"updated_at"`
	NextRunAt     *time.Time `json:"next_run_at"`
	CronStartedAt time.Time  `json:"cron_started_at"`
	Profile       string     `json:"profile"`
	Template      string     `json:"template"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.ID,
		arg.Name,
		arg.Prompt,
		arg.Cron,
		arg.Timezone,
		arg.Status,
		arg.Model,
		arg.SessionMode,
		arg.OwnerEmail,
		arg.Services,
		arg.UpdatedAt,
		arg.NextRunAt,
		arg.CronStartedAt,
		arg.Profile,
		arg.Template,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.Name,
		&i.Prompt,
		&i.Cron,
		&i.Timezone,
		&i.Status,
		&i.Model,
		&i.SessionMode,
		&i.OwnerEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextRunAt,
		&i.CronStartedAt,
		&i.DeletedAt,
		&i.ReusableSessionID,
		&i.ReusableFingerprint,
		&i.Profile,
		&i.Template,
		&i.Services,
	)
	return i, err
}
